(function () {
  function titleCase(value) {
    return String(value)
      .replace(/([a-z])([A-Z])/g, "$1 $2")
      .replace(/[-_]+/g, " ")
      .replace(/\b\w/g, (letter) => letter.toUpperCase());
  }

  function selectOptions(list) {
    return (list || []).map((value) => [value, titleCase(value)]);
  }

  const groupOrder = ["Face", "Skin", "Hair", "Brows", "Eyes", "Nose", "Face Lines", "Cheeks", "Ears", "Mouth", "Teeth", "Jaw", "Chin", "Clothing", "Accessory", "Jewellery", "Beard", "Animation", "Moustache", "Tattoo"];
  const groupTitleMap = {
    "Face Lines": "Skin detail",
    Clothing: "Body",
    Tattoo: "Tattoo list"
  };

  function normalizeTattooList(traits) {
    const t = traits || {};
    if (Array.isArray(t.tattoos) && t.tattoos.length) return t.tattoos.map((item) => ({ ...item }));
    if (!t.tattooText) return [];
    return [{
      text: t.tattooText,
      place: t.tattooPlace || "body",
      font: t.tattooFont || "bold",
      color: t.tattooColor || "#23232b",
      x: Number(t.tattooX) || 0,
      y: Number(t.tattooY) || 0,
      scale: Number(t.tattooScale) || 1,
      rot: Number(t.tattooRot) || 0,
      skewX: Number(t.tattooSkewX) || 0,
      warp: Number(t.tattooWarp) || 0,
      opacity: t.tattooOpacity == null ? 1 : Number(t.tattooOpacity),
      layer: t.tattooLayer || "overClothes"
    }];
  }

  function fieldsForFaceStudio(traitBook, accessoryChoices) {
    return [
      { group: "Face", key: "faceShape", label: "Face Shape", type: "select", options: () => selectOptions(traitBook.faceShapes), fallback: "oval" },
      { group: "Face", key: "headScaleX", label: "Head Width", min: 0.85, max: 1.18, step: 0.01, fallback: 1 },
      { group: "Face", key: "headScaleY", label: "Head Height", min: 0.85, max: 1.18, step: 0.01, fallback: 1 },
      { group: "Face", key: "neckWidth", label: "Neck Width", min: 0.72, max: 1.38, step: 0.01, fallback: 1 },
      { group: "Face", key: "neckLength", label: "Neckline Height", min: -8, max: 16, step: 0.5, fallback: 0 },
      { group: "Face", key: "headTilt", label: "Head Tilt", min: -12, max: 12, step: 0.5, fallback: 0 },
      { group: "Face", key: "headY", label: "Head Position", min: -10, max: 10, step: 1, fallback: 0 },
      { group: "Face", key: "eyeGap", label: "Eye Gap", min: 40, max: 62, step: 1, fallback: 47 },
      { group: "Skin", key: "skin", label: "Skin Tone", type: "select", options: () => selectOptions(traitBook.skinTones), fallback: "fair" },
      { group: "Skin", key: "background", label: "Background", type: "color", fallback: "" },
      { group: "Hair", key: "hair", label: "Hair Style", type: "select", options: () => selectOptions(traitBook.hairStyles), fallback: "messy" },
      { group: "Hair", key: "hairColor", label: "Hair Color", type: "select", options: () => selectOptions(traitBook.hairColors), fallback: "brown" },
      { group: "Hair", key: "hairOutlineMode", label: "Hair Outline", type: "select", options: () => [["on", "On"], ["off", "Off"]], fallback: "on" },
      { group: "Hair", key: "hairOutline", label: "Hair Outline Colour", type: "color", fallback: "" },
      { group: "Hair", key: "frontHairY", label: "Front Hair Y", min: -18, max: 18, step: 1, fallback: 0 },
      { group: "Hair", key: "backHairY", label: "Back Hair Y", min: -14, max: 14, step: 1, fallback: 0,
        when: (t) => ["longWaves", "bun", "hijab"].includes(t.hair) || !(window.facesHair && window.facesHair.has(t.hair)) },
      { group: "Hair", key: "lockBlend", label: "Lock Blending", type: "select", options: () => [["merged", "Merged"], ["separate", "Separate"]], fallback: "merged" },
      { group: "Brows", key: "browShape", label: "Brow Shape", type: "select", options: () => selectOptions(traitBook.browShapes), fallback: "soft" },
      { group: "Brows", key: "browY", label: "Brow Height", min: -6, max: 6, step: 0.5, fallback: 0 },
      { group: "Brows", key: "browScaleX", label: "Brow Width", min: 0.8, max: 1.25, step: 0.02, fallback: 1 },
      { group: "Brows", key: "browThick", label: "Brow Thickness", min: 0.5, max: 2, step: 0.05, fallback: 1 },
      { group: "Brows", key: "browAngle", label: "Brow Angle", min: -25, max: 25, step: 1, fallback: 0 },
      { group: "Brows", key: "browLeftAngle", label: "Left Brow Angle", min: -30, max: 30, step: 1, fallback: 0 },
      { group: "Brows", key: "browRightAngle", label: "Right Brow Angle", min: -30, max: 30, step: 1, fallback: 0 },
      { group: "Eyes", key: "eyeScale", label: "Eye Size", min: 0.7, max: 1.25, step: 0.02, fallback: 0.94 },
      { group: "Eyes", key: "eyeOpen", label: "Eye Openness", min: 0.5, max: 1.2, step: 0.02, fallback: 0.95 },
      { group: "Eyes", key: "irisScale", label: "Iris Size", min: 0.7, max: 1.2, step: 0.02, fallback: 0.92 },
      { group: "Eyes", key: "eyeColor", label: "Iris Colour", type: "color", fallback: "" },
      { group: "Eyes", key: "eyeY", label: "Eye Height", min: -8, max: 8, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeX", label: "Eye Group X", min: -12, max: 12, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeLeftX", label: "Left Eye X", min: -12, max: 12, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeRightX", label: "Right Eye X", min: -12, max: 12, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeLeftY", label: "Left Eye Y", min: -8, max: 8, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeRightY", label: "Right Eye Y", min: -8, max: 8, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "pupilX", label: "Pupil X", min: -5, max: 5, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "pupilY", label: "Pupil Y", min: -5, max: 5, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "lazyEye", label: "Lazy Eye", min: -8, max: 8, step: 0.5, fallback: 0 },
      { group: "Eyes", key: "eyeDart", label: "Eye Movement (dart range)", min: 0, max: 1, step: 0.02, fallback: 0.6 },
      { group: "Eyes", key: "lashes", label: "Eyelashes", min: 0, max: 1.6, step: 0.05, fallback: 0 },
      { group: "Eyes", key: "eyelashThickness", label: "Eyelash Thickness", min: 0.7, max: 4, step: 0.1, fallback: 2 },
      { group: "Eyes", key: "eyelashDensity", label: "Eyelash Density", min: 0.35, max: 2.2, step: 0.05, fallback: 1 },
      { group: "Eyes", key: "eyelashCoverage", label: "Eyelash Coverage", type: "select", options: () => [["quarter", "Quarter Lid"], ["half", "Half Lid"], ["full", "Full Lid"]], fallback: "quarter" },
      { group: "Eyes", key: "eyelashColor", label: "Eyelash Colour", type: "color", fallback: "" },
      { group: "Eyes", key: "eyeshadowOpacity", label: "Eyeshadow", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Eyes", key: "eyeshadowColor", label: "Eyeshadow Colour", type: "color", fallback: "" },
      { group: "Eyes", key: "upperEyelidWidth", label: "Upper Eyelid Width", min: 0.6, max: 3.8, step: 0.1, fallback: 1 },
      { group: "Eyes", key: "lowerEyelidWidth", label: "Lower Eyelid Width", min: 0.5, max: 3, step: 0.1, fallback: 1 },
      { group: "Eyes", key: "undershadowOpacity", label: "Under-eye Shadow", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Eyes", key: "undershadowY", label: "Under-eye Shadow Y", min: -10, max: 8, step: 0.5, fallback: -3 },
      { group: "Eyes", key: "undershadowWidth", label: "Under-eye Shadow Width", min: 0.5, max: 1.8, step: 0.05, fallback: 1 },
      { group: "Eyes", key: "underEyeWidth", label: "Under-eye Line Width", min: 0.5, max: 1.8, step: 0.05, fallback: 1 },
      { group: "Nose", key: "noseY", label: "Nose Height", min: -8, max: 10, step: 0.5, fallback: 0 },
      { group: "Nose", key: "noseScale", label: "Nose Size", min: 0.6, max: 1.5, step: 0.02, fallback: 1 },
      { group: "Nose", key: "noseWidth", label: "Nose Width (skinny ↔ broad)", min: 0.55, max: 1.5, step: 0.02, fallback: 1 },
      { group: "Nose", key: "noseTip", label: "Tip Shape", type: "select", options: () => selectOptions(traitBook.noseTips), fallback: "round" },
      { group: "Face Lines", key: "faceLineOpacity", label: "All Lines (master)", min: 0, max: 1, step: 0.05, fallback: 1 },
      { group: "Face Lines", key: "nasoOpacity", label: "Nasolabial Folds", min: 0, max: 1, step: 0.05, fallback: 0.55 },
      { group: "Face Lines", key: "foreheadLineOpacity", label: "Forehead Wrinkles", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Face Lines", key: "frownLineOpacity", label: "Frown Lines (glabella)", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Face Lines", key: "underEyeOpacity", label: "Under-Eye Bags", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Face Lines", key: "underEyeY", label: "Under-Eye Line Y", min: -10, max: 8, step: 0.5, fallback: -3 },
      { group: "Face Lines", key: "underEyeLineWidth", label: "Under-Eye Line Width", min: 0.6, max: 3, step: 0.1, fallback: 1.3 },
      { group: "Face Lines", key: "crowsFeetOpacity", label: "Crow's Feet", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Face Lines", key: "marionetteOpacity", label: "Marionette Lines", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Face Lines", key: "cheekLineOpacity", label: "Cheek Hollows", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Cheeks", key: "cheekY", label: "Blush Height", min: -8, max: 8, step: 0.5, fallback: 0 },
      { group: "Cheeks", key: "cheekOpacity", label: "Blush", min: 0, max: 0.5, step: 0.01, fallback: 0.09 },
      { group: "Cheeks", key: "blushColor", label: "Blush Colour", type: "color", fallback: "" },
      { group: "Cheeks", key: "blushScale", label: "Blush Size", min: 0.4, max: 2, step: 0.05, fallback: 1 },
      { group: "Cheeks", key: "blushX", label: "Blush Spacing", min: -18, max: 18, step: 0.5, fallback: 0 },
      { group: "Cheeks", key: "contourOpacity", label: "Cheek Contour", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Cheeks", key: "contourY", label: "Contour Y", min: -14, max: 14, step: 0.5, fallback: 0 },
      { group: "Cheeks", key: "contourX", label: "Contour Spacing", min: -18, max: 18, step: 0.5, fallback: 0 },
      { group: "Cheeks", key: "contourWidth", label: "Contour Width", min: 0.55, max: 1.8, step: 0.05, fallback: 1 },
      { group: "Ears", key: "earVariant", label: "Ear Shape", type: "select", options: () => selectOptions(traitBook.earVariants), fallback: "round" },
      { group: "Ears", key: "earScale", label: "Ear Size", min: 0.7, max: 1.3, step: 0.02, fallback: 1 },
      { group: "Ears", key: "earY", label: "Ear Height", min: -10, max: 10, step: 1, fallback: 0 },
      { group: "Ears", key: "earX", label: "Ear Group X", min: -12, max: 12, step: 0.5, fallback: 0 },
      { group: "Ears", key: "earLeftX", label: "Left Ear X", min: -14, max: 14, step: 0.5, fallback: 0 },
      { group: "Ears", key: "earRightX", label: "Right Ear X", min: -14, max: 14, step: 0.5, fallback: 0 },
      { group: "Ears", key: "earLeftY", label: "Left Ear Y", min: -14, max: 14, step: 0.5, fallback: 0 },
      { group: "Ears", key: "earRightY", label: "Right Ear Y", min: -14, max: 14, step: 0.5, fallback: 0 },
      { group: "Ears", key: "earRot", label: "Ear Rotate", min: -20, max: 20, step: 1, fallback: 0 },
      { group: "Mouth", key: "mouthStyle", label: "Smile Style", type: "select", options: () => selectOptions(traitBook.mouthStyles), fallback: "warmSmile" },
      { group: "Mouth", key: "smileLips", label: "Smile Lips", type: "select", options: () => [["on", "On"], ["off", "Off"]], fallback: "on" },
      { group: "Mouth", key: "lips", label: "Lip Shape", type: "select", options: () => selectOptions(traitBook.lipStyles), fallback: "line" },
      { group: "Mouth", key: "lipUpper", label: "Upper Lip Design", type: "select", options: () => selectOptions(traitBook.lipUppers), fallback: "soft" },
      { group: "Mouth", key: "lipLower", label: "Lower Lip Design", type: "select", options: () => selectOptions(traitBook.lipLowers), fallback: "round" },
      { group: "Mouth", key: "lipLineWidth", label: "Lip Line Width", min: 0.3, max: 3, step: 0.05, fallback: 1 },
      { group: "Mouth", key: "lipUpperSize", label: "Upper Lip Size", min: 0.4, max: 1.8, step: 0.05, fallback: 1 },
      { group: "Mouth", key: "lipLowerSize", label: "Lower Lip Size", min: 0.4, max: 1.8, step: 0.05, fallback: 1 },
      { group: "Mouth", key: "smileLowerLipCurve", label: "Smile Lower Lip Curve", min: -0.8, max: 1.4, step: 0.05, fallback: 0 },
      { group: "Mouth", key: "lipColor", label: "Lip Colour", type: "color", fallback: "" },
      { group: "Mouth", key: "mouthOpenW", label: "Open Mouth Width", min: 0.5, max: 1.7, step: 0.05, fallback: 1,
        when: (t) => { const e = (window.faceGenerator && window.faceGenerator.traitBook.expressions) || {}; return !!(e[t.expression] && e[t.expression].openMouth) || ["surprised", "shocked"].includes(t.expression); } },
      { group: "Mouth", key: "mouthOpenH", label: "Open Mouth Height", min: 0.5, max: 1.9, step: 0.05, fallback: 1,
        when: (t) => { const e = (window.faceGenerator && window.faceGenerator.traitBook.expressions) || {}; return !!(e[t.expression] && e[t.expression].openMouth) || ["surprised", "shocked"].includes(t.expression); } },
      { group: "Mouth", key: "mouthY", label: "Mouth Y", min: -16, max: 18, step: 1, fallback: 0 },
      { group: "Mouth", key: "mouthScale", label: "Mouth Size", min: 0.72, max: 1.28, step: 0.02, fallback: 1 },
      { group: "Teeth", key: "teethStyle", label: "Teeth Style", type: "select", options: () => selectOptions(traitBook.teethStyles), fallback: "even" },
      { group: "Teeth", key: "teethGap", label: "Front Gap", min: 0, max: 10, step: 0.5, fallback: 0 },
      { group: "Teeth", key: "teethOverhang", label: "Bucky Overhang", min: 0, max: 14, step: 0.5, fallback: 0 },
      { group: "Teeth", key: "teethX", label: "Teeth X", min: -16, max: 16, step: 1, fallback: 0 },
      { group: "Teeth", key: "teethY", label: "Teeth Y", min: -14, max: 14, step: 1, fallback: 0 },
      { group: "Teeth", key: "teethScale", label: "Teeth Size", min: 0.62, max: 1.38, step: 0.02, fallback: 1 },
      { group: "Jaw", key: "jawLength", label: "Jaw Length", min: -0.25, max: 0.4, step: 0.01, fallback: 0 },
      { group: "Jaw", key: "jawShadowY", label: "Jaw Shadow", min: -6, max: 6, step: 0.5, fallback: 0 },
      { group: "Chin", key: "chinShape", label: "Chin Shape", type: "select", options: () => selectOptions(traitBook.chinShapes), fallback: "none" },
      { group: "Chin", key: "chinY", label: "Chin Height", min: -16, max: 18, step: 1, fallback: 0 },
      { group: "Chin", key: "chinWidth", label: "Chin Width", min: 0.6, max: 1.7, step: 0.02, fallback: 1 },
      { group: "Chin", key: "chinScale", label: "Chin Size", min: 0.5, max: 2, step: 0.02, fallback: 1 },
      { group: "Clothing", key: "clothing", label: "Outfit", type: "select", options: () => selectOptions(traitBook.clothing), fallback: "tee" },
      { group: "Clothing", key: "shirt", label: "Clothing Colour", type: "color", fallback: "" },
      { group: "Clothing", key: "build", label: "Build (shoulder width)", min: 60, max: 100, step: 1, fallback: 82 },
      { group: "Clothing", key: "shoulderSlope", label: "Shoulder Slope", min: 0, max: 1, step: 0.02, fallback: 0.5 },
      { group: "Clothing", key: "bodyWidth", label: "Body Width (torso)", min: 0.7, max: 1.4, step: 0.01, fallback: 1 },
      { group: "Clothing", key: "belly", label: "Belly", min: 0, max: 1, step: 0.05, fallback: 0 },
      { group: "Clothing", key: "bust", label: "Bust", min: 0, max: 1.5, step: 0.05, fallback: 0 },
      { group: "Accessory", key: "accessory", label: "Accessory", type: "select", options: () => selectOptions(accessoryChoices), fallback: "none" },
      { group: "Accessory", key: "accessoryColor", label: "Accessory Colour", type: "color", fallback: "" },
      { group: "Accessory", key: "accessoryMetal", label: "Chain Metal", type: "select", options: () => [["", "Auto"], ["silver", "Silver"], ["gold", "Gold"], ["black", "Black"], ["roseGold", "Rose Gold"]], fallback: "" },
      { group: "Accessory", key: "chainLink", label: "Chain Link Size", min: 0.5, max: 2.2, step: 0.05, fallback: 1 },
      { group: "Accessory", key: "accessoryX", label: "Accessory X", min: -24, max: 24, step: 1, fallback: 0 },
      { group: "Accessory", key: "accessoryY", label: "Accessory Y", min: -24, max: 24, step: 1, fallback: 0 },
      { group: "Accessory", key: "accessoryScale", label: "Accessory Size", min: 0.68, max: 1.36, step: 0.02, fallback: 1 },
      { group: "Accessory", key: "accessoryRot", label: "Accessory Rotate", min: -45, max: 45, step: 1, fallback: 0 },
      { group: "Accessory", key: "accessoryLayer", label: "Accessory Layer", type: "select", options: () => [["auto", "Auto"], ["beforeHead", "Behind Head"], ["behindHair", "Behind Hair"], ["beforeMouth", "Before Mouth"], ["afterMouth", "Front"]], fallback: "auto" },
      { group: "Jewellery", key: "jewellery", label: "Jewellery", type: "select", options: () => selectOptions(traitBook.jewellery || ["none"]), fallback: "none" },
      { group: "Jewellery", key: "jewellerySide", label: "Side", type: "select", options: () => [["both", "Both"], ["left", "Left"], ["right", "Right"]], fallback: "both" },
      { group: "Jewellery", key: "jewelleryColor", label: "Colour", type: "color", fallback: "" },
      { group: "Jewellery", key: "jewelleryColor2", label: "Second Colour", type: "color", fallback: "" },
      { group: "Jewellery", key: "jewelleryMetal", label: "Metal", type: "select", options: () => [["", "Auto"], ["silver", "Silver"], ["gold", "Gold"], ["black", "Black"], ["roseGold", "Rose Gold"]], fallback: "" },
      { group: "Jewellery", key: "jewelleryX", label: "Jewellery X", min: -24, max: 24, step: 1, fallback: 0 },
      { group: "Jewellery", key: "jewelleryY", label: "Jewellery Y", min: -24, max: 24, step: 1, fallback: 0 },
      { group: "Jewellery", key: "jewelleryScale", label: "Jewellery Size", min: 0.5, max: 1.8, step: 0.02, fallback: 1 },
      { group: "Jewellery", key: "jewelleryRot", label: "Jewellery Rotate", min: -45, max: 45, step: 1, fallback: 0 },
      { group: "Jewellery", key: "jewelleryLayer", label: "Jewellery Layer", type: "select", options: () => [["beforeHead", "Behind Head"], ["behindHair", "Behind Hair"], ["beforeMouth", "Before Mouth"], ["afterMouth", "Front"]], fallback: "behindHair" },
      { group: "Beard", key: "beardLength", label: "Beard Length", min: 0, max: 1, step: 0.02, fallback: 0.35 },
      { group: "Beard", key: "beardX", label: "Beard X", min: -18, max: 18, step: 1, fallback: 0 },
      { group: "Beard", key: "beardY", label: "Beard Y", min: -18, max: 22, step: 1, fallback: 0 },
      { group: "Beard", key: "beardScale", label: "Beard Scale", min: 0.72, max: 1.42, step: 0.02, fallback: 1 },
      { group: "Beard", key: "beardSkewX", label: "Beard Skew X", min: -30, max: 30, step: 1, fallback: 0 },
      { group: "Beard", key: "beardSkewY", label: "Beard Skew Y", min: -30, max: 30, step: 1, fallback: 0 },
      { group: "Animation", key: "animMode", label: "Animation", type: "select", options: () => selectOptions(traitBook.animModes), fallback: "still" },
      { group: "Animation", key: "blinkRate", label: "Blink Every (s)", min: 0, max: 12, step: 0.5, fallback: 4.5 },
      { group: "Animation", key: "winkRate", label: "Wink Every (s)", min: 0, max: 30, step: 1, fallback: 0 },
      { group: "Moustache", key: "moustacheX", label: "Moustache X", min: -18, max: 18, step: 1, fallback: 0 },
      { group: "Moustache", key: "moustacheY", label: "Moustache Y", min: -18, max: 18, step: 1, fallback: 0 },
      { group: "Moustache", key: "moustacheScale", label: "Moustache Size", min: 0.62, max: 1.5, step: 0.02, fallback: 1 },
      { group: "Tattoo", key: "tattooText", label: "Text", type: "text", fallback: "" },
      { group: "Tattoo", key: "tattooPlace", label: "Placement", type: "select", options: () => selectOptions(traitBook.tattooPlaces), fallback: "body" },
      { group: "Tattoo", key: "tattooFont", label: "Font", type: "select", options: () => selectOptions(traitBook.tattooFonts), fallback: "bold" },
      { group: "Tattoo", key: "tattooColor", label: "Colour", type: "color", fallback: "" },
      { group: "Tattoo", key: "tattooX", label: "X", min: -70, max: 70, step: 1, fallback: 0 },
      { group: "Tattoo", key: "tattooY", label: "Y", min: -40, max: 20, step: 1, fallback: 0 },
      { group: "Tattoo", key: "tattooScale", label: "Size", min: 0.4, max: 3, step: 0.05, fallback: 1 },
      { group: "Tattoo", key: "tattooRot", label: "Rotate", min: -60, max: 60, step: 1, fallback: 0 },
      { group: "Tattoo", key: "tattooSkewX", label: "Skew", min: -45, max: 45, step: 1, fallback: 0 },
      { group: "Tattoo", key: "tattooWarp", label: "Warp", min: 0, max: 1, step: 0.02, fallback: 0 },
      { group: "Tattoo", key: "tattooOpacity", label: "Fade", min: 0, max: 1, step: 0.05, fallback: 1 }
      ,{ group: "Tattoo", key: "tattooLayer", label: "Layer", type: "select", options: () => [["overClothes", "Over Clothes"], ["onSkin", "On Skin"]], fallback: "overClothes" }
    ];
  }

  window.WhoEditorShared = {
    titleCase,
    selectOptions,
    groupOrder,
    groupTitleMap,
    normalizeTattooList,
    fieldsForFaceStudio
  };
})();
