// ===================================================================================
// GAME DATA — editable content (questions, locations, mode flavour). Safe to edit in a
// separate thread without touching game logic in app.js. Loaded as window.GameData.
// ===================================================================================
window.GameData = {
  // Player question decks ------------------------------------------------------------
  classicPrompts: [
  "Does your person have facial hair?",
  "Is your person wearing glasses?",
  "Does your person have warm-colored hair?",
  "Would your person be described as smiling?",
  "Does your person have an accessory near their head?",
  "Does your person look surprised?",
  "Does your person look angry?",
  "Does your person look sad?",
  "Is your person wearing a hoodie?",
  "Does your person have a head covering?",
  "Does your person have long hair?",
  "Is your person looking directly forward?",
  "Does your person seem older than thirty?",
  "Could your person be described as confident?",
  "Does your person have short hair?",
  "Is your person wearing a bright color?"
],

  absurdPrompts: [
  "How would this person ask for a divorce?",
  "What would this person say in their wedding vows?",
  "What would this person name their boat?",
  "On a dating app, what are this person's three hashtags?",
  "What is the lie this person would be best at selling?",
  "What would this person say if they were caught reading someone else's texts?",
  "What would this person's last message before leaving a group chat say?",
  "What compliment would this person give that somehow sounds like a threat?",
  "What would this person write in an apology note they absolutely did not mean?",
  "How would this person fire someone without technically saying they are fired?",
  "What would this person confess after two glasses of wine?",
  "What would this person say to talk their way out of a parking ticket?",
  "What would this person put in a will that makes the family go silent?",
  "What would this person's fake charity be called?",
  "What is this person's signature move in an argument they are losing?",
  "What would this person say if an ex walked into the room?",
  "What would this person write as the subject line of a very dramatic email?",
  "What rumour would this person accidentally start at a dinner party?",
  "What would this person say while deleting a security camera recording?",
  "What would this person name their memoir?",
  "What would this person's alibi sound like?",
  "How would this person break bad news to someone they secretly dislike?",
  "What would this person say to a neighbour they have been avoiding for six months?",
  "What is the most suspicious thing this person would call \"just a misunderstanding\"?",
  "What would this person say if they were asked to make a toast with no warning?",
  "What would this person's notes app confession look like?",
  "What would this person say to end a date early?",
  "What would this person put on a missing poster for themselves?",
  "How would this person explain a suitcase full of cash?",
  "What would this person say if they were pretending everything was fine?"
],

  // Per-mode question decks (keyed by mystery-effect id) -----------------------------
  modePrompts: {
  yugioh: [
    "Is your person a Monster card?",
    "Is your person a Spell or Trap?",
    "Does your person have more than 2000 ATK?",
    "Is your person's DEF higher than their ATK?",
    "Is your person a DARK attribute?",
    "Is your person a LIGHT attribute?",
    "Is your person Level 5 or higher (would need a Tribute)?",
    "Is your person Level 4 or below?",
    "Is your person an Effect Monster?",
    "Is your person a Normal Monster (no effect)?",
    "Would you Set your person face-down?",
    "Is your person a Continuous card?",
    "Does your person belong in the Graveyard already?",
    "Is your person your opening hand?",
    "Is your person a Dragon-type?",
    "Is your person a Spellcaster-type?",
    "Is your person a Warrior-type?",
    "Would your person survive Mirror Force?",
    "Would your person get hit by Raigeki?",
    "Is your person a Fusion Monster?",
    "Is your person a Ritual Monster?",
    "Could your person be Special Summoned?",
    "Is your person a WATER attribute?",
    "Is your person a FIRE attribute?",
    "Is your person an EARTH attribute?",
    "Is your person a WIND attribute?",
    "Would you tribute your person for something better?",
    "Is your person a Quick-Play Spell?",
    "Is your person a Counter Trap?",
    "Is your person a Field Spell?",
    "Is your person an Equip card?",
    "Is your person banished from play?",
    "Would your person top the meta?",
    "Is your person a brick in your hand?",
    "Does your person have exactly 8 stars?",
    "Is your person a beatstick with no effect?",
    "Would you side-deck your person out?",
    "Is your person a hand trap?",
    "Is your person worth a Pot of Greed?",
    "Does your person negate effects?",
    "Is your person immune to destruction by battle?",
    "Would Exodia be embarrassed by your person?",
    "Is your person a Machine-type?",
    "Is your person a Fiend-type?",
    "Is your person a Zombie-type?",
    "Would your person get Solemn Judgment'd?",
    "Is your person's ATK a multiple of 500?",
    "Is your person searchable from the deck?",
    "Would you draw into your person turn one?",
    "Is your person banlist-worthy?",
    "Is your person a floodgate?",
    "Does your person have a summoning condition?",
    "Is your person more DEF than vibes?",
    "Would your person tribute themselves?",
    "Is your person's Level odd?",
    "Does your person belong in an anime filler episode?",
    "Is your person a token?",
    "Would Kaiba pay 8000 LP for your person?",
    "Is your person the heart of the cards?",
    "Does your person read like six paragraphs of text?",
    "Is your person a Synchro (in spirit)?",
    "Is your person an XYZ (in spirit)?",
    "Would your person get Kaiju'd?",
    "Is your person a wall (high DEF, low ATK)?",
    "Is your person a one-card combo?",
    "Would your person survive a board wipe?",
    "Is your person a staple?",
    "Is your person a win condition?",
    "Is your person a searcher?",
    "Would your person mill your deck?",
    "Is your person forbidden?",
    "Is your person limited to one?",
    "Does your person have a twin card?",
    "Is your person a boss monster?",
    "Is your person a generic extender?",
    "Would you banish your person for cost?",
    "Is your person a splashable engine?",
    "Does your person have piercing damage?",
    "Is your person a spirit monster?",
    "Would your person survive Torrential Tribute?",
    "Is your person the ace of the deck?",
    "Is your person a tuner?",
    "Is your person a pendulum (emotionally)?",
    "Does your person tribute the whole field?",
    "Is your person more than one card in a trench coat?",
    "Would you hard-draw your person late game?",
    "Is your person a scam?",
    "Is your person a summon-negate?",
    "Is your person a going-second card?",
    "Is your person a going-first card?",
    "Would Yugi believe in your person?",
    "Is your person a topdeck live?",
    "Is your person a vanilla with a nice picture?",
    "Would your person get Ash Blossom'd?",
    "Is your person the reason you lost?",
    "Does your person deserve a structure deck?",
    "Is your person un-searchable?",
    "Is your person a meme card?",
    "Is your person actually good?"
  ],
  orgy: [
    "Is your person a top?",
    "Is your person a bottom?",
    "Is your person a vers?",
    "Is your person a power bottom?",
    "Is your person a starfish?",
    "Is your person choking someone tonight?",
    "Is your person getting gagged?",
    "Is your person doing the choking?",
    "Is your person's body count over 100?",
    "Is your person's body count over 50?",
    "Is your person's body count in single digits?",
    "Is your person's cum count today above 5?",
    "Has your person finished today at all?",
    "Has your person slept with someone else on this board?",
    "Is your person linked to more than one other player?",
    "Is your person's horniness maxed out?",
    "Does your person have low stamina?",
    "Does your person have high stamina?",
    "Is someone specific UP NEXT for your person?",
    "Is your person keeping a lot of secrets?",
    "Would your person survive the night?",
    "Is your person a giver?",
    "Is your person a taker?",
    "Is your person switch?",
    "Would your person kiss and tell?",
    "Is your person the loudest in the room?",
    "Is your person the quiet one?",
    "Would your person send nudes unprompted?",
    "Is your person somebody's ex?",
    "Is your person somebody's future ex?",
    "Is your person a repeat offender?",
    "Would your person leave immediately after?",
    "Would your person stay for breakfast?",
    "Is your person a cuddler?",
    "Is your person all talk?",
    "Does your person overshare in bed?",
    "Is your person a one-hit wonder?",
    "Would your person go again?",
    "Is your person insatiable?",
    "Does your person have a type?",
    "Is your person everyone's type?",
    "Would your person catch feelings?",
    "Is your person emotionally unavailable?",
    "Is your person here for a good time not a long time?",
    "Is your person a heartbreaker?",
    "Would your person ghost after?",
    "Is your person somebody's secret?",
    "Is your person a homewrecker?",
    "Is your person freaky?",
    "Is your person vanilla?",
    "Would your person try anything once?",
    "Is your person a diva about it?",
    "Is your person a pillow princess?",
    "Is your person a service top?",
    "Would your person top from the bottom?",
    "Is your person a menace?",
    "Is your person surprisingly gentle?",
    "Is your person rough?",
    "Is your person a tease?",
    "Would your person make it weird?",
    "Is your person a screamer?",
    "Would your person leave a hickey?",
    "Is your person clingy?",
    "Is your person avoidant?",
    "Would your person block someone after?",
    "Is your person out of everyone's league?",
    "Would your person rate it 10/10 unprompted?",
    "Is your person somebody's rebound?",
    "Would your person cry after?",
    "Is your person aftercare royalty?",
    "Would your person forget your name?",
    "Does your person keep a spreadsheet?",
    "Is your person somebody's first?",
    "Would your person do a group thing?",
    "Is your person strictly one-on-one?",
    "Is your person a wildcard?",
    "Would your person double-book tonight?",
    "Is your person exhausted by 9pm?",
    "Is your person a night owl?",
    "Would your person send a paragraph after?",
    "Is your person high-maintenance?",
    "Would your person bring snacks?",
    "Would your person survive a threesome?",
    "Is your person the third?",
    "Is your person the couple?",
    "Would your person swipe on everyone here?",
    "Is your person the group's worst decision?",
    "Would your person do it in the kitchen?",
    "Is your person a repeat mistake?",
    "Is your person worth it?",
    "Is your person a red flag in bed?",
    "Would your person film it?",
    "Is your person shy until the lights are off?",
    "Would your person do a walk of shame?",
    "Is your person somebody's situationship?",
    "Would your person define the relationship?",
    "Is your person allergic to labels?",
    "Is your person the reason for the group chat?",
    "Would your person survive dating an ex's friend?",
    "Is your person a serial texter after?"
  ],
  fireworks: [
    "Is your person about to lose their head?",
    "Would your person go out with a bang?",
    "Is your person next on the chopping block?",
    "Does your person deserve to explode?",
    "Would your person make a pretty firework?",
    "Is your person keeping their head down?",
    "Should your person's head pop first?",
    "Is your person a dud or a showstopper?",
    "Would your person spark or fizzle?",
    "Is your person all fuse, no boom?",
    "Would your person light up the sky?",
    "Is your person a sparkler (mild)?",
    "Is your person a mortar (huge)?",
    "Would your person go off early?",
    "Is your person a delayed reaction?",
    "Is your person a firecracker?",
    "Is your person a damp squib?",
    "Would your person take others out with them?",
    "Is your person a solo act?",
    "Is your person the grand finale?",
    "Is your person the opening shot?",
    "Would your person misfire?",
    "Is your person safe to hold?",
    "Is your person a rocket?",
    "Is your person a Catherine wheel?",
    "Would your person leave a crater?",
    "Is your person more smoke than fire?",
    "Would your person startle the dog?",
    "Is your person a health-and-safety nightmare?",
    "Is your person the one that goes sideways?",
    "Would your person clear the room?",
    "Is your person a Roman candle?",
    "Is your person a banger?",
    "Would your person impress the crowd?",
    "Is your person a let-down?",
    "Is your person loud?",
    "Is your person silent-but-deadly?",
    "Would your person need a long fuse?",
    "Is your person volatile?",
    "Is your person stable (for now)?",
    "Would your person combust unprompted?",
    "Is your person the finale you paid for?",
    "Is your person the cheap pack?",
    "Would your person relight?",
    "Is your person a one-and-done?",
    "Would your person shower sparks?",
    "Is your person color-changing?",
    "Is your person just white flash?",
    "Would your person set off car alarms?",
    "Is your person the reason for the recall?",
    "Is your person imported and illegal?",
    "Would your person go off in your hand?",
    "Is your person best from a distance?",
    "Is your person the neighbour's complaint?",
    "Would your person ruin the show?",
    "Is your person the star of the show?",
    "Is your person a slow burn?",
    "Would your person explode on contact?",
    "Is your person a chain reaction?",
    "Is your person the first domino?",
    "Is your person the last?",
    "Would your person leave a mark?",
    "Is your person a whistler?",
    "Would your person crackle?",
    "Is your person a fountain?",
    "Is your person a snake (all smoke)?",
    "Would your person disappoint the kids?",
    "Is your person a professional-grade hazard?",
    "Would your person need a permit?",
    "Is your person the bonfire's main event?",
    "Is your person a backyard disaster?",
    "Would your person take out a fence?",
    "Is your person a repeat firework?",
    "Is your person a single-use joy?",
    "Would your person go up in one go?",
    "Is your person the one everyone films?",
    "Is your person the one everyone boos?",
    "Would your person survive re-lighting?",
    "Is your person the encore?",
    "Is your person overhyped?",
    "Is your person underrated?",
    "Would your person peak too early?",
    "Is your person a satisfying pop?",
    "Is your person a whimper?",
    "Is your person a skyful?",
    "Would your person light the whole box?",
    "Is your person the box everyone avoids?",
    "Is your person the safe sparkler for toddlers?",
    "Would your person go BANG right now?",
    "Is your person still smoking?",
    "Is your person already ash?",
    "Would your person get relaunched next year?",
    "Is your person the one that got away (unlit)?",
    "Would your person blow a fuse?",
    "Is your person a slow drip of sparks?",
    "Would your person survive being dropped?",
    "Would your person need the fire brigade?",
    "Is your person a beautiful disaster?",
    "Is your person a total flop?",
    "Is your person the neighbourhood menace?"
  ],
  "knockoff-manor": [
    "Is your person in the BATHS ROOM?",
    "Is your person in the KITCHEN?",
    "Did your person do it?",
    "Is your person in the same room as the body?",
    "Is your person holding the weapon?",
    "Is your person upstairs?",
    "Is your person downstairs?",
    "Does your person have an alibi (they don't)?",
    "Is your person sweating right now?",
    "Would your person flee the manor?",
    "Is your person covered in blood?",
    "Is your person suspiciously calm?",
    "Is your person hiding something?",
    "Would your person point the finger at someone else?",
    "Is your person the butler?",
    "Is your person the heir?",
    "Was your person near the candlestick?",
    "Was your person near the knife?",
    "Is your person's room next to the body?",
    "Would your person lie to the detective?",
    "Is your person the obvious suspect?",
    "Is your person the least likely suspect?",
    "Does your person have a motive?",
    "Does your person have money troubles?",
    "Would your person inherit everything?",
    "Is your person a guest, not family?",
    "Is your person new to the manor?",
    "Would your person crack under questioning?",
    "Is your person left-handed (like the killer)?",
    "Was your person alone at the time?",
    "Does your person have blood on their cuffs?",
    "Is your person avoiding eye contact?",
    "Would your person tamper with evidence?",
    "Is your person in a locked room?",
    "Is your person the one who found the body?",
    "Would your person raise the alarm or hide it?",
    "Is your person wealthy?",
    "Is your person broke?",
    "Would your person kill for the estate?",
    "Is your person a red herring?",
    "Is your person the real killer?",
    "Does your person know the victim's secret?",
    "Would your person blackmail someone?",
    "Is your person being blackmailed?",
    "Is your person in the wine cellar?",
    "Was your person in the library?",
    "Would your person move the body?",
    "Is your person's story full of holes?",
    "Is your person a smooth liar?",
    "Is your person a terrible liar?",
    "Would your person confess under pressure?",
    "Is your person protecting someone?",
    "Is your person being framed?",
    "Does your person have the missing key?",
    "Is your person the last to see the victim?",
    "Was your person seen near the study?",
    "Would your person poison the tea?",
    "Is your person the family doctor?",
    "Is your person the estranged cousin?",
    "Would your person cut the phone lines?",
    "Is your person snowed in with the rest?",
    "Does your person own a weapon?",
    "Would your person hide the will?",
    "Is your person mentioned in the will?",
    "Is your person cut out of the will?",
    "Would your person disappear before dawn?",
    "Is your person the second victim (soon)?",
    "Is your person the detective's prime suspect?",
    "Would your person survive the night?",
    "Does your person have a convenient twin?",
    "Would your person swap rooms to confuse things?",
    "Is your person hiding a bloody glove?",
    "Is your person the one with the grudge?",
    "Would your person tamper with the clocks?",
    "Is your person's alibi another suspect?",
    "Is your person covering for the killer?",
    "Would your person take the blame for love?",
    "Is your person too helpful to the detective?",
    "Is your person weirdly uninterested?",
    "Would your person flee across the moor?",
    "Is your person hiding in the dumbwaiter?",
    "Is your person the one who screamed?",
    "Is your person the one who didn't scream?",
    "Would your person plant evidence?",
    "Is your person a professional (hired)?",
    "Is your person an amateur (crime of passion)?",
    "Would your person leave a clue on purpose?",
    "Is your person taunting the detective?",
    "Is your person the mastermind?",
    "Is your person the muscle?",
    "Is your person the lookout?",
    "Would your person betray the group?",
    "Is your person the one you'd never suspect?",
    "Would your person survive the sequel?",
    "Is your person the killer's next target?",
    "Is your person in on it?",
    "Is your person completely innocent?",
    "Would your person confess to save another?",
    "Is your person hiding the weapon on them?"
  ],
  "gay-frogged": [
    "Is your person glowing the same colour as yours?",
    "Is your person serving looks?",
    "Does your person top from the bottom?",
    "Is your person a POC icon?",
    "Would your person host the function?",
    "Is your person the mother of the group?",
    "Is your person the messy one?",
    "Would your person start drama?",
    "Is your person giving?",
    "Is your person a neopronoun user?",
    "Would your person read someone to filth?",
    "Is your person the token straight (frogged anyway)?",
    "Is your person camp?",
    "Is your person butch?",
    "Is your person femme?",
    "Would your person lip-sync for their life?",
    "Is your person the group's therapist?",
    "Is your person chronically online?",
    "Would your person cause a scene?",
    "Is your person unbothered?",
    "Is your person the drama?",
    "Would your person spill the tea?",
    "Is your person the peacemaker?",
    "Is your person the instigator?",
    "Would your person go viral?",
    "Is your person iconic?",
    "Is your person problematic?",
    "Would your person cancel someone?",
    "Is your person cancelled?",
    "Is your person beloved?",
    "Would your person die for the aesthetic?",
    "Is your person high-femme?",
    "Is your person a soft boy?",
    "Would your person cry at the club?",
    "Is your person the DD?",
    "Is your person always late?",
    "Would your person overshare?",
    "Is your person the group's chaos?",
    "Is your person the group's stability?",
    "Would your person date within the friend group?",
    "Is your person everyone's ex?",
    "Is your person the newest addition?",
    "Would your person start a podcast?",
    "Is your person the fashion?",
    "Is your person the vibe?",
    "Would your person gatekeep?",
    "Is your person a pick-me?",
    "Is your person effortlessly cool?",
    "Would your person try too hard?",
    "Is your person the group historian?",
    "Would your person keep receipts?",
    "Is your person the one who ghosts?",
    "Is your person the one who double-texts?",
    "Would your person catch a flight not feelings?",
    "Is your person catching feelings?",
    "Is your person the loud one?",
    "Is your person the quiet threat?",
    "Would your person read the room?",
    "Is your person incapable of reading the room?",
    "Would your person throw the party?",
    "Is your person the after-party?",
    "Would your person survive Pride?",
    "Is your person Pride royalty?",
    "Would your person adopt a cause?",
    "Is your person all vibes no politics?",
    "Is your person deeply political?",
    "Would your person date their bestie's ex?",
    "Is your person the glue of the group?",
    "Is your person the wildcard?",
    "Would your person move to Berlin?",
    "Is your person a theatre kid grown up?",
    "Would your person start a group chat war?",
    "Is your person muted in three chats?",
    "Is your person the main character?",
    "Is your person the side quest?",
    "Would your person serve at brunch?",
    "Is your person a brunch menace?",
    "Would your person cry-glow?",
    "Is your person glowing suspiciously bright?",
    "Is your person dimming?",
    "Would your person change colours mid-argument?",
    "Is your person the same colour as their crush?",
    "Would your person deny the glow?",
    "Is your person proud of the glow?",
    "Is your person new to the glow?",
    "Would your person weaponise the glow?",
    "Is your person a glow icon?",
    "Is your person the group's DJ?",
    "Would your person plan the holiday?",
    "Is your person banned from planning?",
    "Is your person the responsible one (shockingly)?",
    "Is your person a red flag in a cute top?",
    "Would your person survive the group holiday?",
    "Is your person the reason for the group holiday?",
    "Would your person start a thirst trap account?",
    "Is your person the wholesome one?",
    "Is your person the freak?",
    "Is your person the one everyone protects?",
    "Would your person die on a hill about brunch?",
    "Is your person the group's chef?"
  ],
  disease: [
    "Is your person's worst condition MEGA?",
    "Is your person's worst condition MAJOR?",
    "Is everything wrong with your person only MINOR?",
    "Does your person have cancer?",
    "Does your person have more than one cancer?",
    "Is your person pregnant?",
    "Is your person's autism above 50%?",
    "Is your person's autism below 20%?",
    "Is your person in serious pain (>:( )?",
    "Is your person having a great day (:D)?",
    "Has your person been diagnosed with Hysteria?",
    "Has your person got the Vapours?",
    "Is your person on more than one medication?",
    "Is your person prescribed leeches?",
    "Is your person prescribed mercury?",
    "Does your person have a terminal estimated arrival?",
    "Is one of your person's conditions on the old DSM?",
    "Would your person survive to next Tuesday?",
    "Does your person have HIV?",
    "Does your person have the plague?",
    "Is your person a walking biohazard?",
    "Is your person's cancer arriving imminently?",
    "Is your person's cancer already here?",
    "Does your person have Drapetomania?",
    "Does your person have Moral Insanity?",
    "Is your person suffering from Wandering Womb?",
    "Does your person have Consumption?",
    "Is your person just tired (Neurasthenia)?",
    "Does your person have Brain Fever?",
    "Does your person have Ennui?",
    "Is your person lovesick?",
    "Is your person's condition contagious?",
    "Would you quarantine your person?",
    "Is your person on radium water?",
    "Is your person taking arsenic?",
    "Is your person on laudanum?",
    "Does your person need bloodletting?",
    "Is your person's autism a perfect 100%?",
    "Does your person have exactly three diagnoses?",
    "Is your person's pain at maximum?",
    "Would your person qualify for hospice?",
    "Is your person cured (they are not)?",
    "Does your person have Affluenza?",
    "Does your person have Scurvy?",
    "Is your person full of bad humours?",
    "Is your person's diagnosis older than germ theory?",
    "Would a Victorian doctor recognise your person?",
    "Is your person's cancer in an odd body part?",
    "Is your person's cancer in the vibe?",
    "Does your person have a wallet cancer?",
    "Is your person on snake oil?",
    "Is your person prescribed electroshock?",
    "Is your person awaiting a lobotomy?",
    "Does your person have a MEGA and a MINOR?",
    "Is your person's worst issue below the neck?",
    "Is your person's worst issue in the head?",
    "Does your person have a condition named after a place?",
    "Is your person's ETA in weeks?",
    "Is your person's ETA in months?",
    "Is your person's ETA next Tuesday?",
    "Would your person's chart make a doctor faint?",
    "Is your person over-medicated?",
    "Is your person under-medicated?",
    "Does your person self-diagnose?",
    "Is your person a hypochondriac (justified)?",
    "Would your person survive the operation?",
    "Is your person's condition the doctor's fault?",
    "Does your person have something they made up?",
    "Is your person allergic to being well?",
    "Does your person have a defect of moral fibre?",
    "Is your person's blood the wrong colour?",
    "Is your person's pain face a straight line?",
    "Is your person smiling through it?",
    "Is your person crying?",
    "Does your person need a second opinion?",
    "Does your person glow with illness?",
    "Is your person's cancer plural?",
    "Is your person's diagnosis fashionable?",
    "Is your person's diagnosis embarrassing?",
    "Would your person be studied for science?",
    "Is your person patient zero?",
    "Is your person a medical marvel?",
    "Is your person a medical disaster?",
    "Does your person rattle when they walk?",
    "Would your person survive a Victorian ward?",
    "Is your person's soul also consumed?",
    "Is your person's fever in the brain?",
    "Is your person mostly bile?",
    "Would your person be bled out?",
    "Is your person recovering (allegedly)?",
    "Is your person getting worse?",
    "Is your person one bad cough from the end?",
    "Would your person be sent to the sanatorium?",
    "Is your person's chart a red flag?",
    "Is your person quarantined already?",
    "Would your person survive their own treatment?",
    "Is your person's cure worse than the disease?",
    "Is your person a cautionary tale?",
    "Is your person's pain purely emotional?",
    "Is your person the ward's favourite?"
  ],
  drugs: [
    "Does your person inject?",
    "Does your person snort?",
    "Does your person smoke it?",
    "Does your person swallow theirs?",
    "Does your person huff?",
    "Does your person drink theirs?",
    "Does your person have more than one habit?",
    "Does your person have three or more habits?",
    "Is your person on the gear?",
    "Is your person on the charlie?",
    "Is your person on the smack?",
    "Is your person on the crank?",
    "Does your person take more than 10 a day?",
    "Does your person take more than 20 a day?",
    "Is your person clean? (they are not)",
    "Would your person share?",
    "Is your person hooked on something you snort?",
    "Is your person hooked on something you smoke?",
    "Would your person huff glue?",
    "Is your person on the poppers?",
    "Is your person on the benzos?",
    "Is your person on the oxys?",
    "Is your person on the molly?",
    "Is your person on the tina?",
    "Is your person on the lean?",
    "Is your person on the spice?",
    "Is your person on the crack?",
    "Is your person on the ket?",
    "Would your person do a bump right now?",
    "Is your person functional?",
    "Is your person a mess?",
    "Would your person sell to fund it?",
    "Is your person somebody's dealer?",
    "Is your person somebody's customer?",
    "Would your person try anything once?",
    "Is your person a needle person?",
    "Is your person strictly a smoker?",
    "Would your person raid the medicine cabinet?",
    "Is your person on whippits?",
    "Is your person on bath salts?",
    "Would your person eat the mystery pill?",
    "Is your person a weekend warrior?",
    "Is your person a daily user?",
    "Is your person on the devil's lettuce?",
    "Would your person pass a drug test? (no)",
    "Is your person in denial?",
    "Is your person proud of it?",
    "Would your person cook it themselves?",
    "Is your person a lightweight?",
    "Is your person tolerance-proof?",
    "Would your person share a needle?",
    "Is your person on the meow meow?",
    "Would your person do it before noon?",
    "Is your person a chaotic user?",
    "Would your person hide it in the bin?",
    "Is your person the reason things go missing?",
    "Is your person always 'about to quit'?",
    "Would your person relapse today?",
    "Is your person on their fifth relapse?",
    "Is your person a functioning addict?",
    "Is your person barely functioning?",
    "Would your person trade their phone for a fix?",
    "Is your person somebody's bad influence?",
    "Is your person somebody's cautionary tale?",
    "Would your person do it in the toilet at work?",
    "Is your person a party liability?",
    "Is your person the party?",
    "Would your person mix them?",
    "Is your person a purist (one drug only)?",
    "Is your person a polydrug menace?",
    "Would your person do it at a funeral?",
    "Is your person always sniffing?",
    "Is your person always nodding?",
    "Would your person raid your bathroom?",
    "Is your person a bin-diver?",
    "Is your person on something legal-ish?",
    "Is your person on something very illegal?",
    "Would your person get searched at the airport?",
    "Is your person somebody's rock bottom?",
    "Would your person promise to stop tomorrow?",
    "Is your person on tabs?",
    "Is your person on beans?",
    "Would your person share the last one?",
    "Is your person greedy with it?",
    "Is your person a gateway to their friends?",
    "Would your person do it in the car?",
    "Is your person a bedroom user?",
    "Would your person deny it to your face?",
    "Is your person a 'just this once' repeat offender?",
    "Is your person a binger?",
    "Would your person steal from family?",
    "Is your person on more than 30 a day?",
    "Is your person somehow still standing?",
    "Would your person survive cold turkey?",
    "Is your person the intervention subject?",
    "Would your person trade the telly?",
    "Is your person known to the chemist?",
    "Would your person relapse at the wedding?",
    "Is your person clean this week only?"
  ],
  fertility: [
    "Is your person barren?",
    "Does your person's count run into the billions?",
    "Is your person's count only in the millions?",
    "Does your person have a product defect?",
    "Is your person's next emptying within the hour?",
    "Is your person's next emptying over a day away?",
    "Does your person have more than 100 eggs?",
    "Does your person have fewer than 20 eggs?",
    "Are your person's swimmers slow?",
    "Is your person a battery farm?",
    "Would you breed your person?",
    "Does your person produce eggs?",
    "Does your person produce cummies?",
    "Does your person somehow produce both?",
    "Is your person's stock expired?",
    "Is your person suspiciously keen?",
    "Are your person's products all duds?",
    "Is your person premium grade (allegedly)?",
    "Does your person risk a two-headed outcome?",
    "Is your person a genetic lucky dip?",
    "Is your person's batch recalled?",
    "Is your person's chromosome count off?",
    "Would your person's kids be a warning label?",
    "Is your person's timer under ten minutes?",
    "Is your person overdue for emptying?",
    "Is your person's count a round number?",
    "Would your person fill a bucket?",
    "Is your person running dry?",
    "Is your person restocking soon?",
    "Is your person's fertility a hazard?",
    "Would your person come with a receipt?",
    "Is your person's yield disappointing?",
    "Is your person overachieving?",
    "Is your person a one-shot?",
    "Is your person a repeat producer?",
    "Would you put your person in the fridge?",
    "Is your person past their use-by date?",
    "Is your person freshly stocked?",
    "Is your person's count higher than their IQ?",
    "Is your person's timer counting down fast?",
    "Is your person's egg quality poor?",
    "Is your person a prize breeder?",
    "Is your person a dud factory?",
    "Would your person's stock be quarantined?",
    "Is your person's yield measured in litres?",
    "Is your person's yield measured in drops?",
    "Would your person empty on schedule?",
    "Is your person always early?",
    "Is your person always late?",
    "Does your person have a defect warning?",
    "Is your person clinically fertile?",
    "Is your person clinically barren?",
    "Would your person populate a village?",
    "Is your person a dead end (genetically)?",
    "Is your person the last of their line?",
    "Would your person's output win a rosette?",
    "Is your person's stock organic?",
    "Is your person free range?",
    "Is your person cage-reared?",
    "Is your person's count in the low millions?",
    "Is your person's count in the high billions?",
    "Would your person overflow?",
    "Is your person conserving?",
    "Is your person's timer already at zero?",
    "Would your person's eggs count on one hand?",
    "Is your person's egg count triple digits?",
    "Is your person a slow producer?",
    "Is your person a rapid producer?",
    "Would you graft your person for stock?",
    "Is your person's yield certified?",
    "Is your person's yield 'as is, no returns'?",
    "Is your person the pick of the litter?",
    "Is your person the runt?",
    "Would your person's line die out?",
    "Is your person's fertility a national resource?",
    "Is your person's fertility a liability?",
    "Is your person's timer suspiciously precise?",
    "Would your person's kids be lucky?",
    "Would your person's kids be cursed?",
    "Is your person a keeper?",
    "Is your person's stock premium?",
    "Is your person's stock bargain-bin?",
    "Would your person empty twice today?",
    "Is your person empty already?",
    "Is your person a fountain?",
    "Is your person a trickle?",
    "Would your person's swimmers finish the race?",
    "Are your person's swimmers going in circles?",
    "Is your person's egg basket full?",
    "Is your person's egg basket empty?",
    "Would your person crash the market?",
    "Is your person the last hope for the species?",
    "Is your person's output export-grade?",
    "Is your person a breeding champion?",
    "Is your person disqualified from breeding?",
    "Would your person's kids sue?",
    "Is your person a fertility myth?",
    "Is your person a fertility warning?",
    "Is your person still in stock?"
  ],
  disguise: [
    "Can you even tell who your person is?",
    "Are your person's eyes giving anything away?",
    "Would you recognise your person at the shops?",
    "Is your person hiding a smile under there?",
    "Could your person rob a bank like this?",
    "Is your person's disguise doing its job?",
    "Are your person's eyes suspicious?",
    "Would your person's own mother know them?",
    "Is your person visibly nervous under there?",
    "Can you see any hair escaping?",
    "Is your person wearing the eye slit?",
    "Is your person in the towel wrap?",
    "Would your person pass a police lineup?",
    "Are your person's eyes tired?",
    "Are your person's eyes wide open?",
    "Would you trust your person like this?",
    "Is your person more hidden than the rest?",
    "Could your person be anyone?",
    "Are your person's eyes the only clue?",
    "Would your person blink first?",
    "Is your person peeking?",
    "Can you guess the mood from the eyes?",
    "Is your person's disguise slipping?",
    "Would your person keep a straight face?",
    "Are your person's eyes lying to you?",
    "Is your person hiding a beard under there?",
    "Would your person sweat through it?",
    "Is your person committed to the bit?",
    "Are your person's eyes doing too much?",
    "Could your person sneak past you?",
    "Is your person unrecognisable?",
    "Would your person give themselves away?",
    "Is your person's eye colour visible?",
    "Are your person's brows showing?",
    "Would your person crack under questioning?",
    "Is your person a master of disguise?",
    "Is your person terrible at this?",
    "Can you read fear in the eyes?",
    "Would your person forget they're disguised?",
    "Is your person over-committed to it?",
    "Are your person's eyes darting?",
    "Is your person staring you down?",
    "Would your person survive a stakeout?",
    "Is your person's cover blown?",
    "Can you spot a familiar feature?",
    "Is your person hiding in plain sight?",
    "Would your person nod if you asked nicely?",
    "Is your person enjoying the anonymity?",
    "Is your person's disguise the best on the board?",
    "Is your person's disguise the worst?",
    "Would your person pass at the airport?",
    "Is your person's wrap coming loose?",
    "Are your person's eyes bloodshot?",
    "Would your person recognise themselves?",
    "Is your person incognito royalty?",
    "Can you tell their gender from the eyes?",
    "Would your person flinch?",
    "Is your person's stare too intense?",
    "Are your person's eyes kind?",
    "Are your person's eyes cold?",
    "Would your person get away with it?",
    "Is your person a suspect?",
    "Is your person a witness?",
    "Can you place those eyes?",
    "Would your person's friends walk past them?",
    "Is your person hiding on purpose?",
    "Are your person's eyes squinting?",
    "Would your person blow their own cover?",
    "Is your person the easiest to guess?",
    "Is your person the hardest to guess?",
    "Can you see makeup around the eyes?",
    "Would your person survive a spotlight?",
    "Is your person doing a voice too?",
    "Are your person's eyes familiar?",
    "Is your person a total mystery?",
    "Would your person unmask if asked?",
    "Is your person's identity leaking?",
    "Can you see relief in the eyes?",
    "Would your person crack a joke under there?",
    "Is your person's disguise flattering?",
    "Can you tell their age from the eyes?",
    "Would your person get recognised by a pet?",
    "Is your person a walking question mark?",
    "Are your person's eyes the wrong colour for them?",
    "Is your person the one you'd never guess?",
    "Would you bet money on who this is?",
    "Can you narrow it to three people?",
    "Is your person impossible to place?",
    "Are your person's lashes a giveaway?",
    "Would your person survive a metal detector?",
    "Are your person's eyes glassy?",
    "Would your person betray themselves laughing?",
    "Is your person a shadow?",
    "Can you match the eyes to a name?",
    "Would your person swap disguises to fool you?",
    "Is your person the calmest under cover?",
    "Is your person the twitchiest?",
    "Are your person's eyes pleading?",
    "Is your person hiding a grin?"
  ],
  work: [
    "Does your person have more than 1000 days left?",
    "Does your person have fewer than 100 days left?",
    "Is your person hiding a shiv?",
    "Would your person survive the winter?",
    "Has your person had any sun this decade?",
    "Is your person planning a tunnel?",
    "Does your person have any eyebrows left?",
    "Is your person an informant?",
    "Would your person trade their bread ration?",
    "Is your person getting out this year?",
    "Is your person a lifer?",
    "Does your person have contraband?",
    "Is your person's stash weaponised?",
    "Would your person snitch to shave off days?",
    "Is your person hoarding cigarettes?",
    "Does your person keep a pet rat?",
    "Is your person brewing hooch?",
    "Would your person share their stash?",
    "Is your person the block boss?",
    "Is your person the new fish?",
    "Would your person survive solitary?",
    "Is your person's sentence over 5000 days?",
    "Is your person's sentence nearly up?",
    "Does your person have a map fragment?",
    "Is your person's stash all shivs?",
    "Would your person dig with a spoon?",
    "Is your person plotting an escape?",
    "Is your person a model prisoner?",
    "Is your person a troublemaker?",
    "Would your person riot?",
    "Is your person owed favours?",
    "Does your person owe favours?",
    "Is your person the camp cook?",
    "Is your person on latrine duty?",
    "Would your person survive the guards?",
    "Is your person a guard's favourite?",
    "Is your person a guard's enemy?",
    "Does your person have a hidden potato?",
    "Is your person's stash edible?",
    "Would your person barter their blanket?",
    "Is your person cold?",
    "Is your person starving?",
    "Would your person eat the mystery stew?",
    "Is your person the block's dealer?",
    "Does your person have a filed-down rebar?",
    "Would your person shank for a smoke?",
    "Is your person keeping a secret diary?",
    "Would your person survive the work quota?",
    "Is your person behind on their quota?",
    "Is your person the fastest digger?",
    "Would your person betray a cellmate?",
    "Is your person loyal to the block?",
    "Would your person take the fall?",
    "Is your person doing someone else's time?",
    "Is your person innocent (allegedly)?",
    "Is your person very guilty?",
    "Would your person make parole?",
    "Is your person a repeat offender?",
    "Would your person go straight outside?",
    "Is your person institutionalised?",
    "Does your person whittle chess pieces?",
    "Is your person the camp barber?",
    "Would your person hide a file in a cake?",
    "Is your person planning a heist for release day?",
    "Is your person the oldest inmate?",
    "Is your person the youngest?",
    "Would your person survive a shakedown?",
    "Is your person hiding something in their bunk?",
    "Does your person have an extra blanket (illegal)?",
    "Would your person trade the rat?",
    "Is your person the block's memory?",
    "Would your person testify?",
    "Is your person a folk hero inside?",
    "Is your person a snitch nobody trusts?",
    "Would your person crack under the guards?",
    "Is your person unbreakable?",
    "Does your person have a smuggled letter?",
    "Is your person waiting on a pardon?",
    "Would your person's pardon ever come?",
    "Is your person forgotten by the outside?",
    "Is your person counting the days out loud?",
    "Would your person survive another winter?",
    "Is your person's stash worth killing for?",
    "Is your person the target of the block?",
    "Would your person tunnel through the wall?",
    "Is your person the one who always gets caught?",
    "Is your person a smooth operator?",
    "Would your person run the black market?",
    "Is your person on their last legs?",
    "Is your person weirdly thriving?",
    "Would your person miss it outside?",
    "Is your person free in spirit (not body)?",
    "Would your person survive the salt mines?",
    "Is your person the strongest in the yard?",
    "Would your person forge papers?",
    "Is your person the debt collector?",
    "Would your person escape on release day anyway?",
    "Is your person the warden's project?",
    "Is your person owed cigarettes?"
  ],
  woke: [
    "Is your person doing the absolute most?",
    "Does your person have a neopronoun?",
    "Is your person a top with a terminal diagnosis?",
    "Is your person hooked on something AND barren?",
    "Would your person trauma-dump on the first date?",
    "Is your person problematic in at least three ways?",
    "Does your person's glow clash with their vibe?",
    "Is your person a MEGA diagnosis away from cancellation?",
    "Is your person both horny and dying?",
    "Would your person put all of this in their bio?",
    "Is your person a bottom on hard drugs?",
    "Does your person glow AND smoke?",
    "Is your person barren but keen?",
    "Is your person's disease MEGA and their count in the billions?",
    "Would your person survive their own lifestyle?",
    "Is your person a walking content warning?",
    "Does your person use they/them and inject?",
    "Is your person the group's biggest liability?",
    "Is your person a vers with a terminal ETA?",
    "Would your person start a GoFundMe for the vibes?",
    "Is your person high, horny, and ill?",
    "Does your person have more habits than eggs?",
    "Is your person a POWER BOTTOM with the plague?",
    "Is your person's pronoun longer than their lifespan?",
    "Would your person livestream all of this?",
    "Is your person a MINOR diagnosis but MAJOR drama?",
    "Does your person glow red AND green?",
    "Is your person somehow thriving?",
    "Is your person a cautionary TED talk?",
    "Would your person out-chaos everyone here?",
    "Is your person a starfish on smack?",
    "Does your person have HIV and a huge count?",
    "Is your person the most 2020s person here?",
    "Would your person say 'it's giving' unprompted?",
    "Is your person a disaster bisexual (frogged)?",
    "Does your person's disease pair with their drug?",
    "Is your person a gagged, drugged, dying icon?",
    "Would your person date everyone on this board?",
    "Is your person the group chat's whole personality?",
    "Is your person a top, an addict, and pregnant?",
    "Does your person have a defect and a neopronoun?",
    "Is your person cancelled and coughing?",
    "Would your person survive a wellness retreat?",
    "Is your person allergic to moderation?",
    "Is your person the reason the party got raided?",
    "Does your person glow while dying?",
    "Is your person insufferable but iconic?",
    "Is your person more chaos than person?",
    "Is your person a vers with no eggs and no sense?",
    "Does your person mix drugs and drama?",
    "Is your person the wokest disaster here?",
    "Would your person tweet through the apocalypse?",
    "Is your person a MEGA everything?",
    "Is your person a MINOR everything (boring)?",
    "Is your person addicted, afflicted, and adored?",
    "Would your person start a substack about it?",
    "Is your person the group's problematic fave?",
    "Is your person barely holding it together?",
    "Does your person have a pronoun for every mood?",
    "Is your person a bottom, a battery farm, and a biohazard?",
    "Would your person cry, glow, and relapse in one night?",
    "Is your person a lot?",
    "Is your person, frankly, too much?",
    "Does your person peak in every category?",
    "Would your person survive being sober?",
    "Is your person a disease, a drug, and a vibe?",
    "Is your person's whole deal exhausting?",
    "Would your person do all of this before noon?",
    "Is your person a walking discourse?",
    "Is your person the reason the group is on a watchlist?",
    "Does your person glow, gag, and grieve?",
    "Is your person a top-tier mess?",
    "Would your person franchise this lifestyle?",
    "Is your person a triple threat (bad kind)?",
    "Is your person the least stable here?",
    "Is your person somehow the most fun?",
    "Would your person die iconic?",
    "Is your person a themed disaster?",
    "Does your person have layers (of problems)?",
    "Is your person a whole situation?",
    "Would your person survive a detox AND a diagnosis?",
    "Is your person the group's final boss?",
    "Is your person just vibes and vices?",
    "Does your person contradict themselves in every stat?",
    "Is your person the reason for the trigger warning?",
    "Would your person put this on a dating profile?",
    "Is your person a beautiful catastrophe?",
    "Is your person peak chaos?",
    "Is your person the wokest, sickest, horniest here?",
    "Would your person headline the mess Olympics?",
    "Is your person a cocktail of every mode?",
    "Is your person unsummarisable?",
    "Does your person need a content warning of their own?",
    "Would your person survive their own biography?",
    "Is your person a genre of person?",
    "Is your person the finale of every mode at once?",
    "Is your person, ultimately, a warning?",
    "Is your person the human embodiment of a red flag?",
    "Would your person put a disclaimer on themselves?"
  ],
  swipe: [
    "Would you swipe right on your person?",
    "Would you swipe LEFT on your person?",
    "Is your person's match over 80%?",
    "Is your person's match under 20%?",
    "Is your person a 100% match?",
    "Is your person more than 20km away?",
    "Is your person less than 5km away?",
    "Does your person have unread messages?",
    "Does your person have more than 50 unread messages?",
    "Is your person verified (blue tick)?",
    "Is your person over 30?",
    "Is your person under 25?",
    "Is your person looking for something casual?",
    "Is your person looking for marriage?",
    "Is your person looking for a situationship?",
    "Is your person here for chaos?",
    "Is your person just here for free food?",
    "Does your person want their ex back?",
    "Is your person's bio a red flag on its own?",
    "Does your person mention their height in the bio?",
    "Would your person text back within the hour?",
    "Would your person leave you on read?",
    "Does your person have a green flag you'd trust?",
    "Does your person have a load-bearing red flag?",
    "Would your person's red flag be a dealbreaker?",
    "Is your person's ick embarrassing?",
    "Would your person's ick put you off?",
    "Would you unmatch your person immediately?",
    "Would you super-like your person?",
    "Is your person out of your league?",
    "Is your person a catfish?",
    "Does your person's photo match the vibe?",
    "Would your person ghost you?",
    "Would your person double-text?",
    "Is your person emotionally available?",
    "Is your person emotionally unavailable?",
    "Would your person split the bill?",
    "Would your person expect YOU to pay?",
    "Is your person a serial monogamist?",
    "Is your person a serial dater?",
    "Would your person meet up this week?",
    "Would your person cancel last minute?",
    "Is your person somebody's ex on here?",
    "Is your person freshly single?",
    "Would your person's mum like you?",
    "Is your person a hopeless romantic?",
    "Is your person a red flag in a green flag's clothing?",
    "Would your person trauma-dump on date one?",
    "Is your person a green flag all round?",
    "Is your person a walking ick?",
    "Does your person still love their ex?",
    "Would your person keep you a secret?",
    "Is your person shopping around?",
    "Would your person swipe on everyone?",
    "Is your person picky?",
    "Would your person marry for the passport?",
    "Is your person a hookup, not a keeper?",
    "Is your person marriage material?",
    "Would your person survive meeting your friends?",
    "Is your person the one that got away?",
    "Would your person catch feelings fast?",
    "Is your person allergic to labels?",
    "Would your person put you in their bio?",
    "Is your person a certified menace?",
    "Would your person bring the drama?",
    "Is your person low maintenance?",
    "Is your person high maintenance?",
    "Would your person forget your name?",
    "Is your person a repeat swipe (you've seen them before)?",
    "Would your person cry on the first date?",
    "Is your person's distance suspiciously close?",
    "Would your person show up late?",
    "Is your person a green-flag texter?",
    "Does your person type 'haha' with no soul?",
    "Would your person send a paragraph at 2am?",
    "Is your person a fixer-upper?",
    "Would you take your person home to meet the family?",
    "Is your person a swipe-right for the plot?",
    "Is your person a hard pass?",
    "Would your person survive a first date with you?",
    "Is your person somebody's situationship already?",
    "Would your person overshare their exes?",
    "Is your person a green flag financially?",
    "Would your person plan the date?",
    "Is your person a menace in the group chat?",
    "Would your person leave you on delivered?",
    "Is your person the type to fumble it?",
    "Would your person be a good text, bad date?",
    "Is your person a good date, bad text?",
    "Would you introduce your person to your ex?",
    "Is your person a rebound?",
    "Would your person forget the date entirely?",
    "Is your person too good to be true?",
    "Would your person ghost then un-ghost?",
    "Is your person a chronic swiper?",
    "Would your person survive a situationship with you?",
    "Is your person the ick personified?",
    "Would you match with your person again?",
    "Is your person worth the km?",
    "Would your person double-book the night?",
    "Is your person a swipe you'd regret?"
  ],
  judgement: [
    "Is your person in HELL?",
    "Is your person in HEAVEN?",
    "Is your person in PURGATORY (limbo)?",
    "Is your person somewhere hot?",
    "Is your person somewhere glorious?",
    "Is your person stuck in a queue?",
    "Is your person at The Lake of Fire?",
    "Is your person on Cloud Nine?",
    "Is your person in The Waiting Room?",
    "Is your person's location on fire?",
    "Does your person have a halo?",
    "Does your person have horns?",
    "Does your person have a '?' over their head?",
    "Is your person's happiness high?",
    "Is your person's happiness rock-bottom?",
    "Is your person miserable?",
    "Is your person blissed out?",
    "Is your person's torment maxed?",
    "Is your person bored out of their mind?",
    "Is your person's circle number above 5?",
    "Is your person in Circle 9 (the worst)?",
    "Is your person in a low circle of Hell?",
    "Is your person on a high tier of Heaven?",
    "Is your person's tier in the single digits?",
    "Is your person over #100,000 in the purgatory queue?",
    "Is your person near the front of the queue?",
    "Would your person like to get off the ride?",
    "Is your person enjoying the ride?",
    "Is your person's thought a complaint?",
    "Is your person's thought a rave review?",
    "Would your person rate the afterlife 0/10?",
    "Would your person rate it 10/10?",
    "Is your person demanding a refund?",
    "Is your person asking for the exit?",
    "Is your person asking for staff?",
    "Is your person having a wonderful eternity?",
    "Is your person feeling sick?",
    "Is your person too warm?",
    "Is your person waiting for a decision?",
    "Is your person's ride too intense?",
    "Is your person at The Brimstone Pits?",
    "Is your person at The Furnace?",
    "Is your person at The Pearly Gates?",
    "Is your person in the Elysian Fields?",
    "Is your person at Divine Customer Service?",
    "Is your person's location grey and dull?",
    "Is your person's location shiny?",
    "Is your person surrounded by flames?",
    "Is your person surrounded by clouds?",
    "Is your person surrounded by fog?",
    "Is your person's halo glowing?",
    "Are your person's horns on show?",
    "Is your person on the naughty list?",
    "Is your person on the nice list?",
    "Would you send your person to Hell yourself?",
    "Does your person deserve Heaven?",
    "Is your person a borderline case (purgatory)?",
    "Would your person appeal the verdict?",
    "Is your person's verdict HELL?",
    "Is your person's verdict HEAVEN?",
    "Is your person's verdict LIMBO?",
    "Is your person's happiness bar mostly full?",
    "Is your person's happiness bar nearly empty?",
    "Is your person more tormented than happy?",
    "Is your person more bored than tormented?",
    "Is your person in the Ironic Punishment Department?",
    "Would your person kill for something to happen?",
    "Has your person been waiting over 100 years?",
    "Is your person's ride worth the wait?",
    "Is your person's gift shop a scam?",
    "Is your person on hold with the afterlife?",
    "Would your person go on the ride again?",
    "Would your person die again happily?",
    "Is your person's eternity boring?",
    "Is your person's eternity agony?",
    "Is your person's eternity paradise?",
    "Is your person hotter than most here?",
    "Is your person happier than most here?",
    "Is your person more bored than most here?",
    "Would your person leave a one-star review?",
    "Would your person leave a five-star review?",
    "Is your person's circle a high number?",
    "Is your person's tier a low number?",
    "Is your person queueing for eternity?",
    "Does your person want to go home?",
    "Is your person at the front of the pearly gates?",
    "Is your person deep in the Inferno?",
    "Is your person on the Coal Face?",
    "Is your person at the Ambrosia Bar?",
    "Is your person in Terminal 0?",
    "Is your person's thought about the toilets?",
    "Is your person's thought about the music?",
    "Would your person prefer Hell (better company)?",
    "Is your person's verdict too harsh?",
    "Is your person's verdict too kind?",
    "Is your person redeemable?",
    "Is your person beyond saving?",
    "Is your person at peace?",
    "Is your person the reason someone else is in Hell?",
    "Would your person swap places with anyone?",
    "Is your person, ultimately, damned?"
  ],
  sims: [
    "Is your person's plumbob RED?",
    "Is your person's plumbob GREEN?",
    "Is your person's plumbob YELLOW?",
    "Is your person about to wet themselves?",
    "Is your person's bladder need critical?",
    "Is your person's hunger bar low?",
    "Is your person starving?",
    "Is your person's social bar empty?",
    "Is your person lonely?",
    "Is your person's fun bar low?",
    "Is your person bored out of their mind?",
    "Is your person WooHoo-ing?",
    "Is your person napping on the floor?",
    "Is your person crying in the shower?",
    "Is your person on fire (or their kitchen is)?",
    "Is your person talking to no one?",
    "Is your person doing something useful?",
    "Is your person doing something chaotic?",
    "Is your person playing chess with the Grim Reaper?",
    "Is your person stuck between two chairs?",
    "Is your person flirting with an object?",
    "Is your person being abducted by aliens?",
    "Is your person broke (negative simoleons)?",
    "Does your person have over \u00a710,000?",
    "Is your person a simoleonaire?",
    "Is your person in debt?",
    "Is your person's career criminal?",
    "Is your person unemployed?",
    "Is your person an astronaut?",
    "Is your person a starving artist?",
    "Is your person an influencer?",
    "Is your person's career respectable?",
    "Would your person survive without cheats?",
    "Is your person one bar away from a breakdown?",
    "Is your person thriving?",
    "Is your person in aspiration failure?",
    "Is your person's mood good?",
    "Is your person's mood tanking?",
    "Would you cancel your person's autonomy?",
    "Is your person doing the dishes autonomously?",
    "Is your person panicking near the pool ladder?",
    "Would your person 'accidentally' get walled in?",
    "Is your person waving their arms and gibbering?",
    "Is your person about to die of embarrassment?",
    "Is your person's need in the red?",
    "Are all your person's needs full but one?",
    "Is your person's fun the problem?",
    "Is your person's hunger the problem?",
    "Is your person's social the problem?",
    "Is your person's bladder the problem?",
    "Would your person survive the night?",
    "Is your person's plumbob spinning happily?",
    "Is your person's simoleon count negative?",
    "Is your person's job a boss-level career?",
    "Is your person watching the cooking channel?",
    "Is your person grieving, then eating cake?",
    "Is your person repairing something dangerous?",
    "Would your person get electrocuted?",
    "Is your person just standing there menacingly?",
    "Is your person aging up at a party?",
    "Is your person scared of their own reflection?",
    "Is your person doing yoga badly?",
    "Is your person's router on fire?",
    "Is your person in the hot tub?",
    "Would your person survive without you intervening?",
    "Is your person's mood red-alert?",
    "Is your person one need away from green?",
    "Is your person a hard worker (good career)?",
    "Is your person coasting (unemployed)?",
    "Is your person rich AND miserable?",
    "Is your person poor BUT happy?",
    "Would your person max out a skill?",
    "Is your person's current action embarrassing?",
    "Is your person's current action wholesome?",
    "Is your person's current action dangerous?",
    "Would your person set the kitchen on fire?",
    "Is your person begging for a need?",
    "Is your person's plumbob a warning sign?",
    "Would your person pee on the floor?",
    "Is your person the drama of the household?",
    "Is your person the responsible Sim?",
    "Is your person a disaster Sim?",
    "Would your person get taken by the Reaper tonight?",
    "Is your person a professional houseguest?",
    "Is your person's balance in the millions?",
    "Would your person survive a house fire?",
    "Is your person building something in the garden?",
    "Is your person's fun dangerously low?",
    "Is your person emotionally green?",
    "Would your person WooHoo in the hot tub?",
    "Is your person's career a corrupt one?",
    "Is your person having a great day?",
    "Is your person having the worst day?",
    "Would your person ignore every need but one?",
    "Is your person a menace in the house?",
    "Is your person the reason for the fire alarm?",
    "Is your person about to age up?",
    "Would your person survive being left alone?",
    "Is your person's plumbob the colour of doom?",
    "Is your person, frankly, a mess?"
  ],
  astrology: [
    "Is your person a fire sign?",
    "Is your person an earth sign?",
    "Is your person an air sign?",
    "Is your person a water sign?",
    "Is your person a Scorpio (obviously)?",
    "Is your person a Gemini (run)?",
    "Is your person a Leo (we know)?",
    "Is your person a Cancer (crying)?",
    "Is your person a Virgo (judging you)?",
    "Is your person a Capricorn (working)?",
    "Is your person an Aries (fighting)?",
    "Is your person a Pisces (dreaming)?",
    "Is your person a Taurus (stubborn)?",
    "Is your person a Libra (can't decide)?",
    "Is your person a Sagittarius (left already)?",
    "Is your person an Aquarius (aloof)?",
    "Is your person's sun sign the same element as yours?",
    "Is Mercury retrograde for your person?",
    "Is your person's Mercury NOT in retrograde?",
    "Does your person's horoscope mention drama?",
    "Is your person 'the main character' today?",
    "Is your person's toxic trait ghosting?",
    "Does your person weaponise therapy speak?",
    "Is your person always the victim?",
    "Does your person love-bomb then vanish?",
    "Is your person emotionally unavailable (and proud)?",
    "Would your person blame Mercury for everything?",
    "Does your person trauma-dump on strangers?",
    "Is your person's aura loud today?",
    "Is your person a walking red flag (astrologically)?",
    "Would you date your person's sign?",
    "Is your person's sign compatible with yours?",
    "Is your person a cardinal sign?",
    "Is your person a fixed sign?",
    "Is your person a mutable sign?",
    "Is your person's rising sign chaotic?",
    "Does your person read too much into a 'k'?",
    "Is your person the drama?",
    "Would your person's ex agree with their horoscope?",
    "Is your person manifesting something delusional?",
    "Does your person keep score?",
    "Is your person a summer sign?",
    "Is your person a winter sign?",
    "Is your person a spring sign?",
    "Is your person an autumn sign?",
    "Is your person's glyph curvy?",
    "Is your person's element hot-headed?",
    "Is your person's element cold?",
    "Would your person start a fight over their star sign?",
    "Is your person insufferable about astrology?",
    "Does your person have 'unread group chat' energy?",
    "Is your person's horoscope a warning?",
    "Would your person ignore your texts as self-care?",
    "Is your person chronically online (astrologically)?",
    "Is your person a pick-me sign?",
    "Is your person the zodiac's problem child?",
    "Would your person survive Mercury retrograde?",
    "Is your person's toxic trait competitiveness?",
    "Does your person gatekeep?",
    "Is your person a serial situationship-er?",
    "Is your person a 'touch grass' candidate?",
    "Is your person ruled by a planet you can name?",
    "Is your person a water sign crying right now?",
    "Is your person a fire sign causing chaos right now?",
    "Is your person's sign a walking ick?",
    "Would your person's horoscope come true?",
    "Is your person a Scorpio in disguise?",
    "Is your person suspiciously calm (still waters)?",
    "Is your person all talk (air sign)?",
    "Is your person grounded (earth sign)?",
    "Is your person's mood the moon's fault?",
    "Would your person blame the stars for a bad text?",
    "Is your person a zodiac villain?",
    "Is your person a zodiac sweetheart?",
    "Is your person's sign known for cheating?",
    "Is your person's sign known for loyalty?",
    "Would your person do a tarot reading unprompted?",
    "Is your person's big three a mess?",
    "Is your person a hopeless romantic (per their sign)?",
    "Is your person cold and calculating (per their sign)?",
    "Does your person's horoscope mention money (lol)?",
    "Is your person the reason for the group's drama?",
    "Would your person survive dating another Scorpio?",
    "Is your person a fire-and-air disaster?",
    "Is your person an earth-and-water softie?",
    "Is your person's sign a red flag on a dating app?",
    "Would you unmatch your person's sign?",
    "Is your person's toxic trait oversharing?",
    "Is your person's toxic trait never texting first?",
    "Does your person romanticise the bare minimum?",
    "Is your person 'unbothered' (lying)?",
    "Is your person's aura beige?",
    "Is your person's aura neon?",
    "Would your person read your birth chart to insult you?",
    "Is your person a cosmic menace?",
    "Is your person, frankly, giving Gemini?",
    "Is your person the horoscope's problem?",
    "Would your person move cities over a bad Mercury?",
    "Is your person a star-sign supremacist?",
    "Is your person, ultimately, a Scorpio thing?"
  ]
},

  // Locations (art paths are derived from `slug` in app.js) --------------------------
  locations: [
  {
    name: "Cafe",
    slug: "cafe",
    prompt: "Mid-morning, the espresso machine hissing, and three conversations pretending not to overhear each other.",
    gayPrompt: "Oat milk, oversharing, and someone crying in the bathroom because a barista was too nice to them.",
    stamp: "Table 4"
  },
  {
    name: "Restaurant",
    slug: "restaurant",
    prompt: "A late dinner service where the wine has loosened tongues and someone has ordered too much.",
    gayPrompt: "The waiter is definitely a part-time drag queen and someone just proposed to their situationship.",
    stamp: "Booth 9"
  },
  {
    name: "Bar",
    slug: "bar",
    prompt: "Last call energy, sticky counters, and at least one story that gets better every time it's told.",
    gayPrompt: "Last call, Charli XCX on the speaker, and someone's ex just walked in with a hotter ex.",
    stamp: "Last call"
  },
  {
    name: "Rooftop",
    slug: "rooftop",
    prompt: "Skyline views, a cocktail nobody finished, and a confession waiting for the right gust of wind.",
    gayPrompt: "Golden hour, someone's crying on cue, and the group photo has three exes and one situationship.",
    stamp: "Level 22"
  },
  {
    name: "Library",
    slug: "library",
    prompt: "Hushed aisles, a dropped book, and somebody very deliberately not making eye contact.",
    gayPrompt: "The library is open, hunty. Reading is what? Fundamental. Yes gawd, somebody is getting dragged through the nonfiction section.",
    stamp: "Reading room"
  },
  {
    name: "Bookstore",
    slug: "bookstore",
    prompt: "Cramped shelves, a misfiled paperback, and two strangers reaching for the same spine.",
    gayPrompt: "Two people reached for the same Roxane Gay and now they're in love. The poetry section is crying.",
    stamp: "Aisle 3"
  },
  {
    name: "Art Gallery",
    slug: "art_gallery",
    prompt: "White walls, free wine, and everyone nodding at a painting nobody understands.",
    gayPrompt: "Free wine, a painting that's just a red square, and three people claiming it changed their life.",
    stamp: "Opening night"
  },
  {
    name: "Museum Lobby",
    slug: "museum_lobby",
    prompt: "Marble floors, a school tour just left, and a meeting that was supposed to look accidental.",
    gayPrompt: "Marble columns, a forbidden tryst near the Grecian urns, and someone is absolutely giving ancient gay panic.",
    stamp: "Main hall"
  },
  {
    name: "Cinema",
    slug: "cinema",
    prompt: "Trailers rolling, popcorn going cold, and the seat that was definitely supposed to stay empty.",
    gayPrompt: "The movie is Brokeback Mountain. Nobody is watching it. Three people are sobbing anyway.",
    stamp: "Screen 6"
  },
  {
    name: "Hotel Lobby",
    slug: "hotel_lobby",
    prompt: "Late check-in, soft lighting, and a receptionist who has seen absolutely everything.",
    gayPrompt: "Late check-in, the concierge is a retired drag queen, and someone definitely booked a room for two without asking.",
    stamp: "Check-in"
  },
  {
    name: "Airport Lounge",
    slug: "airport_lounge",
    prompt: "A delayed flight, free pretzels, and everyone pretending not to listen to the gate announcements.",
    gayPrompt: "A delayed flight to Fire Island, someone's crying in the lounge, and the pretzels are complimentary.",
    stamp: "Gate 14"
  },
  {
    name: "Train Station",
    slug: "train_station",
    prompt: "A platform between departures, a missed connection, and a goodbye running out of minutes.",
    gayPrompt: "A missed connection, a dramatic slow-motion run down the platform, and someone is blasting Celine Dion.",
    stamp: "Platform 2"
  },
  {
    name: "Gym",
    slug: "gym",
    prompt: "Clanging weights, a borrowed towel, and a rivalry nobody admits is a rivalry.",
    gayPrompt: "Everyone is doing bicep curls and nobody is making eye contact and literally everyone is gay.",
    stamp: "Floor 1"
  },
  {
    name: "Yoga Studio",
    slug: "yoga_studio",
    prompt: "Soft mats, deep breaths, and an inner peace that is being severely tested today.",
    gayPrompt: "Downward dog, emotional processing, and a teacher who keeps saying 'release what no longer serves you' directly at one person.",
    stamp: "9am flow"
  },
  {
    name: "Greenhouse",
    slug: "greenhouse",
    prompt: "Warm glass, dripping ferns, and a quiet argument held just out of earshot.",
    gayPrompt: "Warm glass, rare orchids, and two plant dads having a passive-aggressive disagreement about moisture levels.",
    stamp: "East wing"
  },
  {
    name: "Park",
    slug: "park",
    prompt: "A bench, a shared bag of chips, and a secret that's about to be very badly kept.",
    gayPrompt: "Picnic blankets, a frisbee nobody asked for, and a group chat meltdown happening in real time.",
    stamp: "The green"
  },
  {
    name: "Beach",
    slug: "beach",
    prompt: "Low tide, a dying bonfire, and a long weekend with too many people and one locked beach house.",
    gayPrompt: "Fire Island energy: a locked beach house, a cooler full of seltzers, and someone already crying by 2pm.",
    stamp: "Low tide"
  },
  {
    name: "Diner",
    slug: "diner",
    prompt: "Three a.m., bottomless coffee, and a confession that only makes sense under fluorescent light.",
    gayPrompt: "Post-club fries, somebody's mascara is now a statement, and the waitress has emotionally adopted all of you.",
    stamp: "Counter seat"
  },
  {
    name: "Wine Cellar",
    slug: "wine_cellar",
    prompt: "Cool stone, a dusty vintage, and a toast to something neither of you can name yet.",
    gayPrompt: "An unrequested sommelier monologue, a 'we should just split a bottle' that means everything, and one very load-bearing candle.",
    stamp: "Reserve list"
  },
  {
    name: "Bakery",
    slug: "bakery",
    prompt: "Warm glass, the last croissant, and two polite people each refusing to be the one who takes it.",
    gayPrompt: "A sourdough situationship, a barista writing the wrong name on purpose, and someone openly weeping over a perfectly laminated pastry.",
    stamp: "Fresh batch"
  },
  {
    name: "Nightclub",
    slug: "nightclub",
    prompt: "Two a.m., a bassline you can feel in your teeth, and a glance held three seconds too long across the floor.",
    gayPrompt: "The DJ dropped a remix nobody asked for, two exes are voguing competitively, and someone has lost a shoe to the fog machine.",
    stamp: "Coat check"
  },
  {
    name: "Karaoke",
    slug: "karaoke",
    prompt: "A private room, a sticky remote, and a duet that means far more than either of you will admit.",
    gayPrompt: "Someone queued 'Defying Gravity' unironically and the room has gone silent with reverence. A tambourine has entered the chat.",
    stamp: "Room 3"
  },
  {
    name: "Casino",
    slug: "casino",
    prompt: "No clocks, no windows, and a bet placed on something far riskier than the table.",
    gayPrompt: "Someone's playing blackjack in full sequins, blowing on the dice 'for luck,' and going all in over purely emotional stakes.",
    stamp: "High roller"
  },
  {
    name: "Record Store",
    slug: "record_store",
    prompt: "Crates to flip through, a song you both somehow know, and a hand brushing the same sleeve.",
    gayPrompt: "Someone is gatekeeping a record they found yesterday, and the clerk just diagnosed your entire personality from one purchase.",
    stamp: "New arrivals"
  },
  {
    name: "Theater",
    slug: "theater",
    prompt: "House lights dimming, a held breath, and a seat squeeze right as the curtain lifts.",
    gayPrompt: "It's a one-person show about grief and the lead is somebody's ex. Three rows are sobbing purely on principle.",
    stamp: "Orchestra"
  },
  {
    name: "Arcade",
    slug: "arcade",
    prompt: "Quarter-fed machines, a shared high score, and a rivalry that's clearly about something else.",
    gayPrompt: "A duel for the Dance Dance Revolution crown while a third person narrates it like a championship final.",
    stamp: "High score"
  },
  {
    name: "Bowling Alley",
    slug: "bowling_alley",
    prompt: "Rented shoes, a gutter ball, and a high-five that lingers a beat too long.",
    gayPrompt: "Bumper bowling, a team name change mid-game, and someone winning purely on the strength of the outfit.",
    stamp: "Lane 7"
  },
  {
    name: "Ferry",
    slug: "ferry",
    prompt: "Open water, a shared railing, and a wind that makes leaning in look accidental.",
    gayPrompt: "Someone's doing the Titanic pose unprompted, the gulls have chosen violence, and a long-distance thing is being renegotiated over seltzer.",
    stamp: "Upper deck"
  },
  {
    name: "Pier",
    slug: "pier",
    prompt: "Carnival lights, a shared funnel cake, and a Ferris wheel that stalls at the very top.",
    gayPrompt: "A rigged ring toss, a giant stuffed animal won out of spite, and a confession timed perfectly with the fireworks.",
    stamp: "Boardwalk"
  },
  {
    name: "Spa",
    slug: "spa",
    prompt: "Low light, eucalyptus, and a silence that says more than the small talk did.",
    gayPrompt: "Cucumber water, a face-mask confession, and someone treating a wellness day like court-ordered couples therapy.",
    stamp: "Quiet hour"
  },
  {
    name: "Hair Salon",
    slug: "hair_salon",
    prompt: "Mirror talk, a transformation underway, and a confession that only happens mid-blowout.",
    gayPrompt: "A breakup haircut in progress, the stylist is somehow also a licensed therapist, and everyone's getting bangs out of solidarity.",
    stamp: "Chair 2"
  },
  {
    name: "Tattoo Parlor",
    slug: "tattoo_parlor",
    prompt: "A buzzing needle, a permanent decision, and someone holding a hand 'for the pain.'",
    gayPrompt: "A matching-tattoo idea on a three-week situationship, the artist quietly staging an intervention, and someone crying that it 'doesn't even hurt.'",
    stamp: "Walk-in"
  },
  {
    name: "Office",
    slug: "office",
    prompt: "After hours, monitors still glowing, and a deadline that's become an excuse to stay.",
    gayPrompt: "An after-hours 'quick question,' a situationship conducted entirely in Slack, and HR is absolutely going to hear about this.",
    stamp: "Late shift"
  },
  {
    name: "Aquarium",
    slug: "aquarium",
    prompt: "Blue light, a slow drift of fish, and a hand that almost reaches for another in the dark.",
    gayPrompt: "The jellyfish tank is serving ethereal, someone's crying at the sea turtles, and a first date is going suspiciously, alarmingly well.",
    stamp: "Deep tank"
  },
  {
    name: "Farmers Market",
    slug: "farmers_market",
    prompt: "Morning stalls, a sample offered, and a hand-off of fruit that lasts a second too long.",
    gayPrompt: "An heirloom-tomato bidding war, a tote bag that says everything, and someone catching feelings for the man selling honey.",
    stamp: "Stall 12"
  },
  {
    name: "Ski Lodge",
    slug: "ski_lodge",
    prompt: "Snow on the glass, a crackling fire, and two people who got 'too tired' to ski.",
    gayPrompt: "Nobody actually skied. There's mulled wine, a shared blanket, and a deeply intense group conversation about everyone's attachment style.",
    stamp: "Fireside"
  },
  {
    name: "Hot Spring",
    slug: "hot_spring",
    prompt: "Rising steam, a quiet soak, and a closeness the cold air outside can't explain.",
    gayPrompt: "An accidental couples' soak, a conversation more honest than anyone will admit to later, and lanterns setting the mood unfairly.",
    stamp: "The springs"
  },
],

  // Yu-Gi-Oh 'Field Spell' location reskin -------------------------------------------
  yugiohField: {
    suffixes: ["of the Forbidden Memory", "of Eternal Duels", "of the Shadow Realm", "of Ascended Destiny",
    "of the Sacred Beasts", "of Infinite Tribute", "of the Millennium Gate", "of Roaring Fate"],
    lines: [
    "Once per turn, the duelist who controls this field may banish all hesitation from their hand.",
    "While this card remains face-up, every glance counts as a Tribute. Destiny is not negotiable.",
    "A field where the heart of the cards beats loudest — and secrets are paid as a cost.",
    "Activate this Field Spell to draw one truth. Your opponent cannot respond to the awkwardness.",
    "It's your move. The shadows lengthen, the crowd holds its breath, and someone is bluffing.",
    "This card cannot be destroyed by social niceties. Believe in the heart of the cards.",
    "Send one assumption to the graveyard, then Special Summon a brand-new suspicion in its place."]
  },

  // Disease Mode data ----------------------------------------------------------------------------
  // Deliberately outdated / un-medical "diagnoses" (old DSM-style) plus a couple of real heavy ones.
  // tier: MINOR | MAJOR | MEGA
  diseases: [
    ["Homosexuality", "MAJOR"], ["Hysteria", "MINOR"], ["Drapetomania", "MAJOR"],
    ["Moral Insanity", "MAJOR"], ["Inadequate Personality", "MINOR"], ["Neurasthenia", "MINOR"],
    ["Melancholia", "MINOR"], ["The Vapours", "MINOR"], ["Wandering Womb", "MAJOR"],
    ["Affluenza", "MINOR"], ["Gout", "MINOR"], ["Consumption", "MAJOR"], ["Brain Fever", "MAJOR"],
    ["Lovesickness", "MINOR"], ["Ennui", "MINOR"], ["Scurvy", "MINOR"], ["Bad Humours", "MINOR"],
    ["HIV", "MEGA"], ["Bubonic Plague", "MEGA"], ["Consumption of the Soul", "MEGA"],
    ["Nervous Exhaustion", "MINOR"], ["Excess of Bile", "MINOR"], ["Female Hysteria", "MAJOR"]
  ],
  cancerTypes: ["Lung", "Pancreatic", "Skin", "Bone", "Brain", "Liver", "Stomach", "Throat",
    "Blood", "Colon", "Eyeball", "Elbow", "Vibe", "Wallet", "Spleen"],
  cancerEtas: ["3 weeks", "6 months", "18 months", "by 2030", "imminent", "Q3", "next Tuesday",
    "any day now", "already here", "5–7 business days"],
  medications: ["Mercury Tonic", "Heroic Cough Syrup", "Radium Water", "Cocaine Drops",
    "Leeches (3x daily)", "Laudanum", "Arsenic Wafers", "Lithium Soda", "Snake Oil", "Bloodletting",
    "Tobacco Smoke Enema", "Morphine Lozenge", "Electroshock (PRN)", "Lobotomy (pending)",
    "Strychnine Pick-Me-Up", "Cod Liver Oil", "Opium Tincture", "Vibes (untested)"],
  // Pain faces from worst (left) to best (right).
  painFaces: [">:(", ">:|", ":|", ":)", ":D"],

  // Drug Addict Mode data ------------------------------------------------------------------------
  // Street names only, paired with how they take it.
  drugs: [
    ["Smack", "inject"], ["Gear", "inject"], ["Crank", "inject"], ["Tina", "inject"],
    ["Charlie", "snort"], ["Bugle", "snort"], ["Ket", "snort"], ["Special K", "snort"],
    ["Crack", "smoke"], ["Rock", "smoke"], ["Brown", "smoke"], ["Spice", "smoke"], ["Reefer", "smoke"],
    ["Molly", "swallow"], ["Mandy", "swallow"], ["Tabs", "swallow"], ["Beans", "swallow"],
    ["Vallies", "swallow"], ["Benzos", "swallow"], ["Oxys", "swallow"], ["Lean", "drink"],
    ["Poppers", "huff"], ["Glue", "huff"], ["Gas", "huff"], ["Whippits", "huff"], ["Meow Meow", "snort"],
    ["Bath Salts", "snort"], ["Devil's Lettuce", "smoke"], ["Jenkem", "huff"]
  ],
  drugMethods: {
    inject: "💉 inject", snort: "👃 snort", smoke: "🚬 smoke",
    swallow: "💊 swallow", drink: "🥤 drink", huff: "🫁 huff"
  },

  // Work Mode (gulag) contraband stash items ------------------------------------------------------
  workInventory: ["Sharpened spoon", "Shiv", "Toothbrush shank", "Loose cigarettes", "Homemade hooch",
    "Smuggled letter", "Bent nail", "Soap-on-a-rope (weapon)", "Stale bread crust", "Stolen lighter",
    "Map fragment", "Razor blade", "Salt ration", "Tunnel spoon", "Photo of the outside",
    "Filed-down rebar", "Extra blanket (illegal)", "Pet rat", "Whittled chess set", "Hidden potato",
    "Semi-used condom", "Fortnite-themed bong", "Crusty sock", "Cursed monkey's paw", "Half a mars bar",
    "Someone else's dentures", "A single wet wipe", "Contraband vape", "Suspicious jar", "Toenail collection"],

  // SWIPE Mode (dating app) pools -----------------------------------------------------------------
  swipeLookingFor: ["Something casual", "Marriage tbh", "A situationship", "Nothing serious",
    "Pure chaos", "My ex, ideally", "A green flag", "Free food", "A gym partner", "Someone to fix",
    "The one", "A hall pass", "Just here to watch"],
  swipeBios: [
    "6'0 because apparently it matters.", "I'll never text first but I'll like your posts.",
    "Dog mum. Wine aunt. Emotionally unavailable.", "Just ask, I'm not writing an essay.",
    "Fluent in sarcasm and overthinking.", "Looking for my partner in crime (light crime).",
    "My love language is leaving you on read.", "Swipe left if you chew loudly.",
    "Not here for hookups (available for hookups).", "I peaked in 2016 and I'm working on it.",
    "Ask me about my podcast.", "Therapist says I'm 'a lot'.", "Down for anything except commitment.",
    "I will steal your hoodie.", "Emotionally fluent, financially not.", "Here to lower your standards.",
    "My red flags are load-bearing.", "I do bits.", "Professional yapper.", "Certified menace <3",
    "I bring the vibes and the trust issues.", "Will trauma-dump on date one.", "Just vibes and a vape.",
    "My ick list is longer than my bio.", "Serial monogamist between relationships."],
  swipeGreenFlags: ["Texts back within the hour", "Has a savings account", "Kind to waiters",
    "Actually calls their mum", "No exes in the group chat", "Owns a plant that's alive",
    "Can parallel park", "Splits the bill", "Communicates like an adult", "Great with dogs",
    "Has hobbies that aren't the gym", "Remembers your coffee order", "No unfinished tattoos",
    "Left on good terms with every ex", "Reads actual books"],
  swipeRedFlags: ["Still loves their ex", "Says 'I'm not like other people'", "Has a finsta for the drama",
    "Owns a snake named after a demon", "Calls their mum 'bro'", "Three phones, one job",
    "'I don't really do labels'", "Bites their ice cream", "Argues with strangers online",
    "Peaked in high school", "Has a body count spreadsheet", "Ghosted their own therapist",
    "Screenshots everything", "Lives with an ex 'as friends'", "Vapes indoors"],
  swipeIcks: ["Runs for the bus", "Says 'no worries if not'", "Calls dinner 'din dins'",
    "Trips and looks back at the pavement", "Can't open a jar", "Types 'haha' with no emotion",
    "Wears a suit that doesn't fit", "Struggles with the card machine", "Waves back at the wrong person",
    "Laughs at their own jokes first", "Chases a dropped chip", "Says 'periodt'",
    "Gets excited about a spreadsheet", "Air-drums at traffic lights", "Refers to himself in third person"],

  // JUDGEMENT DAY pools ---------------------------------------------------------------------------
  judgementCauses: ["Choked on a grape", "Selfie gone wrong", "Fell off an e-scooter",
    "Trusted the wrong mushroom", "Vending machine tipped over", "Died of embarrassment (literally)",
    "Bear attack (they started it)", "Escalator incident", "Ate the gas-station sushi",
    "Petting a raccoon", "Stood up too fast", "Struck by a falling piano", "Karma, mostly",
    "Ran with scissors", "Deep-fried a frozen turkey", "Trusted 'it's fine'", "Old age (allegedly)",
    "Duel at dawn", "Autocorrect misunderstanding", "Testing if it was loaded", "Choked laughing",
    " Signal fully green", "Licked a 9-volt battery", "Death by PowerPoint", "Cursed treasure"],
  judgementSins: ["Gluttony", "Greed", "Lust", "Wrath", "Envy", "Pride", "Sloth", "Vanity",
    "Talking in the cinema", "Replying-all", "Left one star reviews", "Ghosting", "Not tipping",
    "Spoiling the ending", "Parking across two spaces", "Microwaving fish at work",
    "Slow-walking in the fast lane", "Saying 'per my last email'", "Doubled-dipped"],
  judgementDeeds: ["Held a door once", "Returned the trolley", "Tipped 20% that one time",
    "Rescued a spider", "Gave good directions", "Let someone merge", "Fed a stray cat",
    "Didn't reply-all", "Split the bill fairly", "Called their nan", "Donated a fiver",
    "Gave up their seat", "Left a nice review", "Actually recycled", "Forgave a debt of £3"],
  // Afterlife "theme park" locations + RollerCoaster-Tycoon-style guest thoughts, keyed by verdict.
  judgementLocations: {
    HEAVEN: ["Cloud Nine", "The Pearly Gates", "Elysian Fields", "The Golden Meadow", "Harp Recital Hall",
      "The Ambrosia Bar", "Seventh Heaven", "The Choir Loft", "Paradise Gardens", "The Light"],
    HELL: ["The Lake of Fire", "The Brimstone Pits", "The Furnace", "Sulphur Springs", "The Boiling Sea",
      "The Ironic Punishment Dept.", "Damnation Alley", "The Inferno", "The Coal Face", "Perdition Plaza"],
    PURGATORY: ["The Waiting Room", "The Limbo Queue", "Reception (Level 0)", "The Holding Pen",
      "The Queue That Never Moves", "Divine Customer Service", "The Grey Lounge", "Terminal 0",
      "The On-Hold Music Room", "The DMV of the Damned"]
  },
  judgementThoughts: {
    HEAVEN: ["Cloud Nine is the best ride in the park!", "I'm having a wonderful eternity.",
      "The Pearly Gates was worth the wait.", "I could stay here forever. Oh wait, I will.",
      "Where can I get some ambrosia?", "The harp music is a bit much, but I love it.",
      "This is the nicest queue I've ever been in.", "10/10, would die again.", "Everything is so shiny!",
      "I feel great! No notes.", "The angels are so friendly.", "Best afterlife ever!"],
    HELL: ["I'd like to get off The Lake of Fire, please.", "I'm not paying £5 for eternal damnation!",
      "I can't find the exit to Hell.", "The queue for the Furnace is way too long.",
      "I feel sick after The Brimstone Pits.", "This ride is TOO intense.", "I want to go home.",
      "It's a bit warm in here.", "I've been on hold with Divine Customer Service for 400 years.",
      "The gift shop is a scam.", "I need the toilet and there aren't any.", "0/10, would not recommend."],
    PURGATORY: ["I've been in this queue for 400 years.", "Is this ride ever going to start?",
      "I want to get off, but there's nothing to get off.", "How much longer is the wait?",
      "The on-hold music is killing me. Again.", "I'm SO bored.", "Has anyone seen a member of staff?",
      "I just want a decision, honestly.", "This is worse than the DMV.", "Please, just send me anywhere.",
      "The magazines here are from 1974.", "I'd kill for something to happen."]
  },

  // SIMS Mode pools -------------------------------------------------------------------------------
  simsActions: ["WooHoo-ing", "Napping on the floor", "Crying in the shower", "About to wet themselves",
    "Talking to no one", "Setting the kitchen on fire", "Autonomously doing the dishes",
    "Panicking near the pool ladder", "Playing chess with the Grim Reaper", "Waving arms and gibbering",
    "Stuck between two chairs", "Watching the cooking channel", "Flirting with a lamp",
    "Building a rocket in the garden", "Getting abducted by aliens", "Screaming at a burnt meal",
    "Doing yoga badly", "Filling every need but bladder", "Aging up at a birthday",
    "Being scared by their own reflection", "Router is on fire", "Woohooing in the hot tub",
    "Grieving, then eating cake", "Repairing the sink (electrocution risk)", "Just standing there menacingly"],
  simsCareers: ["Culinary", "Criminal (Boss)", "Astronaut", "Painter (starving)", "Tech Guru",
    "Secret Agent", "Entertainer", "Politician (corrupt)", "Doctor", "Gardener", "Influencer",
    "Business (mailroom)", "Athlete", "Freelance disaster", "Unemployed", "Professional houseguest",
    "Worker (Sex)"],
  // Witness Protection: the (redacted) reason each protected witness is in the programme.
  witnessReasons: ["Child Killer", "Mall Shooter", "Biden Supporter", "Serial Arsonist", "Tax Fraud (huge)",
    "Cannibal (allegedly)", "Crypto Rug-Puller", "Cult Leader", "Ate the last slice", "Snitched on the mob",
    "Insider Trader", "Ponzi Schemer", "Poisoned the punch", "Doomsday Prepper", "Voted twice",
    "Necromancer", "Robbed a Greggs", "Leaked the finale", "War Criminal (minor)", "Bit a police horse"],
  // Astrology mode: signs (glyph + element), horoscopes, toxic traits.
  astrologySigns: [
    ["Aries", "♈", "Fire"], ["Taurus", "♉", "Earth"], ["Gemini", "♊", "Air"], ["Cancer", "♋", "Water"],
    ["Leo", "♌", "Fire"], ["Virgo", "♍", "Earth"], ["Libra", "♎", "Air"], ["Scorpio", "♏", "Water"],
    ["Sagittarius", "♐", "Fire"], ["Capricorn", "♑", "Earth"], ["Aquarius", "♒", "Air"], ["Pisces", "♓", "Water"]
  ],
  astrologyHoroscopes: [
    "Today you will ignore three texts and call it self-care.",
    "The universe says stop. You will not.",
    "A Gemini will wrong you. Trust no one.",
    "Mercury is retrograde and so is your ex.",
    "You are the drama. Own it.",
    "Big 'main character' energy, zero follow-through.",
    "The stars align for a bad decision at 2am.",
    "Your aura is loud and slightly annoying today.",
    "Manifest gently; the void is not taking requests.",
    "A situationship ends. A worse one begins.",
    "You'll romanticise doing the bare minimum.",
    "The moon dares you to reply-all.",
    "Financially, the cards say 'lol'.",
    "You will win an argument no one was having.",
    "Rest is for the weak, says your rising sign.",
    "Someone is thinking about you. It's HR.",
    "Your energy is 'unread group chat'.",
    "The cosmos suggests touching grass. You won't."
  ],
  astrologyToxic: ["ghosts everyone", "weaponises therapy speak", "always the victim", "love-bombs then vanishes",
    "keeps score", "trauma-dumps on strangers", "never texts first (on principle)", "gatekeeps everything",
    "makes it a competition", "starts the drama, plays innocent", "emotionally unavailable & proud",
    "blames Mercury for everything", "reads too much into a 'k'", "cannot be criticised", "chronic over-sharer"],

  // Horny Potter: four houses (name, colour, crest, bedroom vibe), wand parts, and REAL spells with
  // filthy interpretations. Death Eaters get Unforgivable Curses instead.
  hpHouses: [
    ["Gryffindor", "#7a0f18", "🦁", "reckless, loud, absolutely will not use a safe word"],
    ["Slytherin", "#0f5132", "🐍", "a natural dom, ambitious in every position"],
    ["Hufflepuff", "#c79a1e", "🦡", "unexpectedly filthy, extremely giving, cries after"],
    ["Ravenclaw", "#1c3f70", "🦅", "read the manual, then wrote a better one"]
  ],
  hpWandWoods: ["Elder", "Holly", "Yew", "Vine", "Hawthorn", "Blackthorn", "Cherry", "Willow", "Ebony", "Walnut", "Rosewood", "Cedar", "Cypress", "Hornbeam"],
  hpWandCores: ["dragon heartstring", "phoenix feather", "unicorn hair", "veela hair", "thestral tail-hair"],
  hpWandFlex: ["unyielding", "surprisingly girthy", "quite bendy", "rigid", "swishy", "unusually thick", "throbbing"],
  hpSpells: [
    ["Engorgio", "makes it noticeably bigger"],
    ["Erecto", "gets it right up"],
    ["Reducio", "a delicate size adjustment"],
    ["Alohomora", "unlocks absolutely anything"],
    ["Immobulus", "freeze — right there"],
    ["Silencio", "safe word revoked"],
    ["Petrificus Totalus", "a full-body bind"],
    ["Incendio", "starts a fire down below"],
    ["Rictusempra", "relentless, merciless tickling"],
    ["Aguamenti", "makes everything very wet"],
    ["Relashio", "unties the ropes"],
    ["Descendo", "goes all the way down"],
    ["Duro", "turns it to solid stone"],
    ["Lumos", "turns them right on"],
    ["Accio", "come here. now."],
    ["Stupefy", "leaves them stunned and limp"],
    ["Tarantallegra", "uncontrollable leg-spreading"],
    ["Spongify", "soft, bouncy, forgiving"],
    ["Episkey", "fixes whatever you broke"],
    ["Confundo", "dazed, giggly and willing"],
    ["Finite Incantatem", "okay, okay — we're done"],
    ["Expecto Patronum", "finishes with a real flourish"]
  ],
  hpDarkSpells: [
    ["Imperio", "total, absolute control"],
    ["Crucio", "consensual pain play only"],
    ["Avada Kedavra", "the little death"],
    ["Sectumsempra", "leaves lasting marks"],
    ["Morsmordre", "summons the whole party"]
  ],
  hpPatronuses: [
    "a wet raccoon mid-breakdown", "an incel pigeon", "a screaming goat", "a single soggy Pringle",
    "a dolphin with rabies", "a possessed Furby", "a deflating sex doll", "an emotional-support wasp",
    "a horny manatee", "a seagull that stole your chips", "a feral hamster on meth", "a limp eel",
    "a crying Chihuahua in a handbag", "a goose with an OnlyFans", "a pigeon with one leg and a plan",
    "a hairless cat that hates you", "a moth drawn to bad decisions", "a swan that's been through it",
    "a ferret on its third energy drink", "a possum playing dead to avoid plans"
  ],
  hpBoggarts: [
    "their own search history", "a surprise group FaceTime", "their mum reading their DMs",
    "the words 'we need to talk'", "a wasp in the car at 70mph", "a read receipt with no reply",
    "being perceived in public", "an empty vape", "the dead group chat", "a smear test",
    "their ex's hotter new partner", "a landlord 'inspection'", "running out of data at 40%",
    "a spider in the shower", "commitment", "'per my last email'", "a full voicemail box",
    "eye contact", "their childhood bedroom", "a full-length mirror under strip lighting"
  ],
  hpHorcruxes: [
    "a buttplug", "a literal concentration camp", "Tony (the tiger)", "a taxidermied rat",
    "a cursed Fleshlight", "a single lonely AirPod", "a 'Live Laugh Love' sign", "his childhood retainer",
    "a jar of assorted teeth", "an inflatable doll named Deborah", "a Funko Pop of himself",
    "grandma's ashes (in a Pringles tube)", "a haunted Alexa", "a bag of human hair",
    "a signed Piers Morgan headshot", "the Cybertruck", "a crusty gaming chair", "his own 23andMe results",
    "a taxidermied ferret in a waistcoat", "a McDonald's ball-pit ball"
  ],

  // Disguise mode: rough phonetic spellings so you can 'pronounce' the covered name.
  disguisePhonetic: {},

  // Themed question decks for SWIPE / Judgement Day / Sims are added at the end of modePrompts.
  _modePools: true
};
